import type { Product } from './api';

// Premium Wine & Spirits Dataset - Curated Collection of Investment-Grade Products
export const products: Product[] = [
  // === BORDEAUX FIRST GROWTHS ===
  {
    id: "65b69384-5c21-4f17-b4cc-66a4c526178c",
    name: "Château Lafite Rothschild 2010",
    description: "The epitome of Bordeaux elegance, this legendary First Growth showcases exceptional terroir expression with decades of aging potential.",
    type: "wine",
    varietal: "Cabernet Sauvignon Blend",
    region: "Pauillac, Bordeaux",
    appellation: "Pauillac AOC",
    vintage: 2010,
    producer: "Château Lafite Rothschild",
    alcohol_content: 13.5,
    volume_ml: 750,
    base_price: 1255,
    current_price: 1285,
    price_change_24h: 2.4,
    fiveYearPriceChangePct: 45.2,
    slug: "chateau-lafite-rothschild-2010",
    average_rating: 4.9,
    total_reviews: 127,
    wine_spectator_score: 98,
    robert_parker_score: 97,
    primary_image_url: "/images/wines/lafite-2010.jpg",
    image_urls: ["/images/wines/lafite-2010.jpg", "/images/wines/lafite-2010-bottle.jpg"],
    tasting_notes: "Blackcurrant, cedar, graphite, with an incredibly long and refined finish. Shows classic Lafite elegance with power.",
    food_pairings: ["Prime ribeye steak", "Roasted rack of lamb", "Aged Roquefort cheese"],
    serving_temperature: "60-65°F",
    aging_potential: "30-50 years",
    vineyard_location: "Pauillac, Left Bank Bordeaux",
    estate_history: "Founded in the 17th century, owned by the Rothschild family since 1868",
    production_methods: "Traditional Bordeaux methods, 18-20 months in new French oak",
    certifications: ["AOC Pauillac", "Organic practices"],
    available_quantity: 6,
    minimum_order_quantity: 1,
    last_traded_price: 1270,
    price_range_52week: { low: 1180, high: 1320 },
    volume_traded_24h: 12,
    seller: {
      id: "seller-bordeaux-1",
      business_name: "Bordeaux Fine Wine Merchants",
      seller_rating: 4.9,
      license_number: "TTB-FR-001234",
      license_state: "CA",
      verification_status: "verified",
      years_in_business: 25,
      total_sales: 3847
    },
    requires_adult_signature: true,
    shipping_restrictions: ["Cannot ship to UT", "Cannot ship to AL"],
    ttb_approved: true,
    created_at: new Date('2024-01-15'),
    updated_at: new Date('2024-06-20'),
    featured: true,
    rarity_score: 9.8,
    investment_grade: true
  },
  {
    id: "b86b486f-9514-4fb5-a024-48572d1e5fcc",
    name: "Château Mouton Rothschild 2016",
    description: "Bold and opulent First Growth with distinctive artistic labels, representing the pinnacle of Pauillac winemaking.",
    type: "wine",
    varietal: "Cabernet Sauvignon Blend",
    region: "Pauillac, Bordeaux",
    appellation: "Pauillac AOC",
    vintage: 2016,
    producer: "Château Mouton Rothschild",
    alcohol_content: 14.0,
    volume_ml: 750,
    base_price: 850,
    current_price: 875,
    price_change_24h: 2.9,
    fiveYearPriceChangePct: 32.8,
    slug: "chateau-mouton-rothschild-2016",
    average_rating: 4.8,
    total_reviews: 89,
    wine_spectator_score: 96,
    robert_parker_score: 95,
    primary_image_url: "/images/wines/mouton-2016.jpg",
    image_urls: ["/images/wines/mouton-2016.jpg"],
    tasting_notes: "Cassis, tobacco leaf, with an opulent and powerful texture. Classic Mouton richness and depth.",
    food_pairings: ["Grilled lamb chops", "Wild game", "Strong cheeses"],
    serving_temperature: "60-65°F",
    aging_potential: "25-40 years",
    vineyard_location: "Pauillac, Left Bank Bordeaux",
    available_quantity: 8,
    minimum_order_quantity: 1,
    last_traded_price: 860,
    price_range_52week: { low: 800, high: 920 },
    seller: {
      id: "seller-bordeaux-1",
      business_name: "Bordeaux Fine Wine Merchants",
      seller_rating: 4.9,
      license_number: "TTB-FR-001234",
      license_state: "CA",
      verification_status: "verified",
      years_in_business: 25,
      total_sales: 3847
    },
    requires_adult_signature: true,
    ttb_approved: true,
    created_at: new Date('2024-02-10'),
    updated_at: new Date('2024-06-20'),
    featured: true,
    rarity_score: 9.6,
    investment_grade: true
  },

  // === DRC BURGUNDY ===
  {
    id: "258361bc-12d4-4b3d-9110-539f14cf8adf",
    name: "Domaine de la Romanée-Conti Romanée-Conti 2016",
    description: "The most legendary vineyard in Burgundy, producing wines of unparalleled elegance and complexity. Last vintage before replanting.",
    type: "wine",
    varietal: "Pinot Noir",
    region: "Vosne-Romanée, Burgundy",
    appellation: "Romanée-Conti Grand Cru",
    vintage: 2016,
    producer: "Domaine de la Romanée-Conti",
    alcohol_content: 13.0,
    volume_ml: 750,
    base_price: 25000,
    current_price: 26500,
    price_change_24h: 6.0,
    fiveYearPriceChangePct: 89.3,
    slug: "drc-romanee-conti-2016",
    average_rating: 5.0,
    total_reviews: 45,
    wine_spectator_score: 100,
    robert_parker_score: 98,
    primary_image_url: "/images/wines/drc-rc-2016.jpg",
    image_urls: ["/images/wines/drc-rc-2016.jpg"],
    tasting_notes: "Exotic spice, rose petals, with an ethereal length that defies description. Pure liquid poetry.",
    food_pairings: ["Roasted duck breast", "Truffle dishes", "Aged Burgundy cheese"],
    serving_temperature: "55-60°F",
    aging_potential: "50+ years",
    vineyard_location: "Monopole vineyard in Vosne-Romanée",
    estate_history: "Legendary vineyard dating back to 13th century monks",
    production_methods: "Biodynamic viticulture, minimal intervention winemaking",
    certifications: ["Biodynamic", "Grand Cru AOC"],
    available_quantity: 2,
    minimum_order_quantity: 1,
    last_traded_price: 25800,
    price_range_52week: { low: 23000, high: 28000 },
    volume_traded_24h: 3,
    seller: {
      id: "seller-burgundy-1",
      business_name: "Burgundy Rare Wine Specialists",
      seller_rating: 5.0,
      license_number: "TTB-FR-005678",
      license_state: "NY",
      verification_status: "verified",
      years_in_business: 30,
      total_sales: 1247
    },
    requires_adult_signature: true,
    ttb_approved: true,
    created_at: new Date('2024-01-20'),
    updated_at: new Date('2024-06-20'),
    featured: true,
    rarity_score: 10.0,
    investment_grade: true
  },

  // === NAPA CULT WINES ===
  {
    id: "2632169f-d879-4be3-8100-2be94d9e3361",
    name: "Screaming Eagle Cabernet Sauvignon 2019",
    description: "The most coveted Napa Valley wine, from a tiny vineyard producing only 500 cases annually. Pure Oakville terroir expression.",
    type: "wine",
    varietal: "Cabernet Sauvignon",
    region: "Oakville, Napa Valley",
    appellation: "Oakville AVA",
    vintage: 2019,
    producer: "Screaming Eagle",
    alcohol_content: 15.2,
    volume_ml: 750,
    base_price: 3800,
    current_price: 3950,
    price_change_24h: 3.9,
    fiveYearPriceChangePct: 67.1,
    slug: "screaming-eagle-cabernet-sauvignon-2019",
    average_rating: 4.9,
    total_reviews: 67,
    wine_spectator_score: 98,
    robert_parker_score: 97,
    james_suckling_score: 99,
    primary_image_url: "/images/wines/screaming-eagle-2019.jpg",
    image_urls: ["/images/wines/screaming-eagle-2019.jpg"],
    tasting_notes: "Blackberry, crème de cassis, with plush tannins and incredible depth. Pure Napa Valley power with finesse.",
    food_pairings: ["Dry-aged ribeye", "Venison medallions", "Dark chocolate desserts"],
    serving_temperature: "62-67°F",
    aging_potential: "20-30 years",
    vineyard_location: "Oakville, Napa Valley - single vineyard",
    production_methods: "Hand-harvested, French oak aging, minimal intervention",
    available_quantity: 4,
    minimum_order_quantity: 1,
    last_traded_price: 3875,
    price_range_52week: { low: 3600, high: 4200 },
    seller: {
      id: "seller-napa-1",
      business_name: "Napa Valley Cult Wine Collective",
      seller_rating: 4.8,
      license_number: "TTB-CA-009876",
      license_state: "CA",
      verification_status: "verified",
      years_in_business: 18,
      total_sales: 2156
    },
    requires_adult_signature: true,
    ttb_approved: true,
    created_at: new Date('2024-03-15'),
    updated_at: new Date('2024-06-20'),
    featured: true,
    rarity_score: 9.7,
    investment_grade: true
  },

  // === JAPANESE WHISKY ===
  {
    id: "35670ca7-bc3f-433c-81d4-50058157f363",
    name: "Yamazaki 55 Year Old",
    description: "The pinnacle of Japanese whisky craftsmanship, aged for over half a century. Only 100 bottles ever released worldwide.",
    type: "spirits",
    varietal: "Single Malt Whisky",
    region: "Osaka, Japan",
    vintage: 1960,
    producer: "Suntory",
    alcohol_content: 46.0,
    volume_ml: 750,
    base_price: 600000,
    current_price: 625000,
    price_change_24h: 4.2,
    fiveYearPriceChangePct: 234.7,
    slug: "yamazaki-55-year-old",
    average_rating: 5.0,
    total_reviews: 12,
    primary_image_url: "/images/spirits/yamazaki-55.jpg",
    image_urls: ["/images/spirits/yamazaki-55.jpg", "/images/spirits/yamazaki-55-box.jpg"],
    tasting_notes: "Layered sandalwood, tropical fruit, with incredible complexity built over 55 years of maturation.",
    food_pairings: ["Dark chocolate truffles", "Aged wagyu beef", "Traditional kaiseki"],
    serving_temperature: "Room temperature, neat",
    aging_potential: "Ready to drink, will continue to evolve",
    vineyard_location: "Yamazaki Distillery, Osaka Prefecture",
    production_methods: "Traditional Scottish methods adapted to Japanese climate",
    certifications: ["Japanese Single Malt", "Limited Edition"],
    available_quantity: 1,
    minimum_order_quantity: 1,
    last_traded_price: 615000,
    price_range_52week: { low: 580000, high: 650000 },
    volume_traded_24h: 1,
    seller: {
      id: "seller-spirits-1",
      business_name: "Rare Spirits International",
      seller_rating: 5.0,
      license_number: "TTB-JP-001122",
      license_state: "NY",
      verification_status: "verified",
      years_in_business: 22,
      total_sales: 892
    },
    requires_adult_signature: true,
    ttb_approved: true,
    created_at: new Date('2024-01-10'),
    updated_at: new Date('2024-06-20'),
    featured: true,
    rarity_score: 10.0,
    investment_grade: true
  },

  // === MACALLAN RARE ===
  {
    id: "5df35afa-34e3-40c7-aee1-2bb0317a28f2",
    name: "Macallan 1926 Fine & Rare",
    description: "The most expensive whisky ever sold at auction. From the legendary 1926 vintage, representing the absolute pinnacle of Scotch whisky.",
    type: "spirits",
    varietal: "Single Malt Scotch",
    region: "Speyside, Scotland",
    vintage: 1926,
    producer: "The Macallan",
    alcohol_content: 42.6,
    volume_ml: 750,
    base_price: 2700000,
    current_price: 2850000,
    price_change_24h: 5.6,
    fiveYearPriceChangePct: 187.4,
    slug: "macallan-1926-fine-rare",
    average_rating: 5.0,
    total_reviews: 8,
    primary_image_url: "/images/spirits/macallan-1926.jpg",
    image_urls: ["/images/spirits/macallan-1926.jpg"],
    tasting_notes: "Dried fruit, resin, antique oak with layers of complexity that defy description after nearly a century.",
    food_pairings: ["Best enjoyed neat", "Dark chocolate", "Cigars"],
    serving_temperature: "Room temperature, neat",
    aging_potential: "Peak maturity reached",
    vineyard_location: "Easter Elchies House, Speyside",
    production_methods: "Traditional pot still distillation, sherry cask maturation",
    certifications: ["Single Malt Scotch", "Vintage 1926"],
    available_quantity: 1,
    minimum_order_quantity: 1,
    last_traded_price: 2750000,
    price_range_52week: { low: 2500000, high: 2900000 },
    seller: {
      id: "seller-spirits-2",
      business_name: "Auction House Spirits",
      seller_rating: 5.0,
      license_number: "TTB-UK-003344",
      license_state: "NY",
      verification_status: "verified",
      years_in_business: 35,
      total_sales: 456
    },
    requires_adult_signature: true,
    ttb_approved: true,
    created_at: new Date('2024-02-01'),
    updated_at: new Date('2024-06-20'),
    featured: true,
    rarity_score: 10.0,
    investment_grade: true
  },

  // === PAPPY VAN WINKLE ===
  {
    id: "cc4f7cf6-4bef-4f26-b576-9e493b8c5222",
    name: "Pappy Van Winkle Family Reserve 23 Year",
    description: "The most sought-after bourbon in America, aged 23 years and released in extremely limited quantities annually.",
    type: "spirits",
    varietal: "Wheated Bourbon",
    region: "Kentucky, USA",
    producer: "Old Rip Van Winkle Distillery",
    alcohol_content: 47.8,
    volume_ml: 750,
    base_price: 5200,
    current_price: 5450,
    price_change_24h: 4.8,
    fiveYearPriceChangePct: 78.9,
    slug: "pappy-van-winkle-family-reserve-23-year",
    average_rating: 4.9,
    total_reviews: 234,
    primary_image_url: "/images/spirits/pappy-23.jpg",
    image_urls: ["/images/spirits/pappy-23.jpg"],
    tasting_notes: "Vanilla, oak, caramel with incredible smoothness and complexity from 23 years of aging.",
    food_pairings: ["BBQ brisket", "Pecan pie", "Dark chocolate"],
    serving_temperature: "Room temperature or with single ice cube",
    aging_potential: "Peak maturity, ready to drink",
    vineyard_location: "Stitzel-Weller Distillery heritage",
    production_methods: "Wheated bourbon mash bill, charred oak barrels",
    certifications: ["Kentucky Straight Bourbon", "23 Year Age Statement"],
    available_quantity: 3,
    minimum_order_quantity: 1,
    last_traded_price: 5300,
    price_range_52week: { low: 4800, high: 5800 },
    seller: {
      id: "seller-bourbon-1",
      business_name: "Kentucky Bourbon Specialists",
      seller_rating: 4.9,
      license_number: "TTB-KY-005566",
      license_state: "KY",
      verification_status: "verified",
      years_in_business: 15,
      total_sales: 1876
    },
    requires_adult_signature: true,
    ttb_approved: true,
    created_at: new Date('2024-03-01'),
    updated_at: new Date('2024-06-20'),
    featured: true,
    rarity_score: 9.5,
    investment_grade: true
  },

  // === BATCH 1: PREMIUM CHAMPAGNE & BURGUNDY ===
  {
    id: "batch1-001",
    name: "Dom Pérignon Vintage 2013",
    description: "The pinnacle of Champagne excellence, showcasing perfect balance of power and finesse from an exceptional vintage.",
    type: "wine",
    varietal: "Chardonnay & Pinot Noir Blend",
    region: "Épernay, Champagne",
    appellation: "Champagne AOC",
    vintage: 2013,
    producer: "Dom Pérignon",
    alcohol_content: 12.5,
    volume_ml: 750,
    base_price: 285,
    current_price: 295,
    price_change_24h: 3.5,
    fiveYearPriceChangePct: 28.7,
    slug: "dom-perignon-vintage-2013",
    average_rating: 4.8,
    total_reviews: 156,
    wine_spectator_score: 95,
    robert_parker_score: 94,
    primary_image_url: "/images/wines/dom-perignon-2013.jpg",
    image_urls: ["/images/wines/dom-perignon-2013.jpg"],
    tasting_notes: "Brioche, white flowers, citrus zest with fine bubbles and incredible length. Classic Dom Pérignon elegance.",
    food_pairings: ["Oysters", "Caviar", "Lobster thermidor"],
    serving_temperature: "46-50°F",
    aging_potential: "15-20 years",
    vineyard_location: "Grand Cru vineyards in Champagne",
    estate_history: "Founded by Dom Pierre Pérignon in 1668, part of LVMH luxury group",
    production_methods: "Traditional méthode champenoise, aged on lees for 8+ years",
    certifications: ["Champagne AOC", "Vintage"],
    available_quantity: 12,
    minimum_order_quantity: 1,
    last_traded_price: 290,
    price_range_52week: { low: 270, high: 310 },
    seller: {
      id: "seller-champagne-1",
      business_name: "Champagne House Direct",
      seller_rating: 4.9,
      license_number: "TTB-FR-002345",
      license_state: "NY",
      verification_status: "verified",
      years_in_business: 20,
      total_sales: 2456
    },
    requires_adult_signature: true,
    ttb_approved: true,
    created_at: new Date('2024-04-01'),
    updated_at: new Date('2024-06-20'),
    featured: true,
    rarity_score: 8.5,
    investment_grade: true
  },
  {
    id: "batch1-002",
    name: "Krug Grande Cuvée 171ème Édition",
    description: "The most prestigious non-vintage Champagne, blending over 120 wines from 12 different years for unparalleled complexity.",
    type: "wine",
    varietal: "Chardonnay, Pinot Noir & Pinot Meunier",
    region: "Reims, Champagne",
    appellation: "Champagne AOC",
    producer: "Krug",
    alcohol_content: 12.0,
    volume_ml: 750,
    base_price: 195,
    current_price: 205,
    price_change_24h: 5.1,
    fiveYearPriceChangePct: 42.3,
    slug: "krug-grande-cuvee-171eme-edition",
    average_rating: 4.9,
    total_reviews: 89,
    wine_spectator_score: 96,
    robert_parker_score: 95,
    primary_image_url: "/images/wines/krug-grande-cuvee.jpg",
    image_urls: ["/images/wines/krug-grande-cuvee.jpg"],
    tasting_notes: "Hazelnut, honey, spices with incredible depth and persistence. A symphony of flavors and textures.",
    food_pairings: ["Foie gras", "Turbot", "Aged Comté cheese"],
    serving_temperature: "50-54°F",
    aging_potential: "20+ years",
    vineyard_location: "Premier and Grand Cru vineyards across Champagne",
    estate_history: "Founded in 1843, family-owned house known for prestige cuvées",
    production_methods: "Individual plot fermentation, extensive reserve wine library",
    certifications: ["Champagne AOC", "Prestige Cuvée"],
    available_quantity: 8,
    minimum_order_quantity: 1,
    last_traded_price: 200,
    price_range_52week: { low: 185, high: 220 },
    seller: {
      id: "seller-champagne-1",
      business_name: "Champagne House Direct",
      seller_rating: 4.9,
      license_number: "TTB-FR-002345",
      license_state: "NY",
      verification_status: "verified",
      years_in_business: 20,
      total_sales: 2456
    },
    requires_adult_signature: true,
    ttb_approved: true,
    created_at: new Date('2024-04-05'),
    updated_at: new Date('2024-06-20'),
    featured: true,
    rarity_score: 9.0,
    investment_grade: true
  },
  {
    id: "batch1-003",
    name: "Domaine Armand Rousseau Gevrey-Chambertin 2019",
    description: "From one of Burgundy's most revered producers, this village wine showcases the essence of Gevrey-Chambertin terroir.",
    type: "wine",
    varietal: "Pinot Noir",
    region: "Gevrey-Chambertin, Burgundy",
    appellation: "Gevrey-Chambertin AOC",
    vintage: 2019,
    producer: "Domaine Armand Rousseau",
    alcohol_content: 13.5,
    volume_ml: 750,
    base_price: 450,
    current_price: 485,
    price_change_24h: 7.8,
    fiveYearPriceChangePct: 65.4,
    slug: "armand-rousseau-gevrey-chambertin-2019",
    average_rating: 4.7,
    total_reviews: 67,
    wine_spectator_score: 93,
    robert_parker_score: 92,
    primary_image_url: "/images/wines/rousseau-gevrey.jpg",
    image_urls: ["/images/wines/rousseau-gevrey.jpg"],
    tasting_notes: "Red berries, earth, subtle oak with silky tannins. Classic Gevrey power with Rousseau elegance.",
    food_pairings: ["Coq au vin", "Duck confit", "Époisses cheese"],
    serving_temperature: "60-65°F",
    aging_potential: "15-25 years",
    vineyard_location: "Village and Premier Cru vineyards in Gevrey-Chambertin",
    estate_history: "Family domaine since 1954, one of Burgundy's most respected producers",
    production_methods: "Traditional Burgundian methods, minimal intervention",
    certifications: ["AOC Gevrey-Chambertin", "Organic practices"],
    available_quantity: 6,
    minimum_order_quantity: 1,
    last_traded_price: 470,
    price_range_52week: { low: 420, high: 520 },
    seller: {
      id: "seller-burgundy-1",
      business_name: "Burgundy Rare Wine Specialists",
      seller_rating: 5.0,
      license_number: "TTB-FR-005678",
      license_state: "NY",
      verification_status: "verified",
      years_in_business: 30,
      total_sales: 1247
    },
    requires_adult_signature: true,
    ttb_approved: true,
    created_at: new Date('2024-04-10'),
    updated_at: new Date('2024-06-20'),
    featured: false,
    rarity_score: 8.8,
    investment_grade: true
  },
  {
    id: "batch1-004",
    name: "Hennessy Paradis",
    description: "A masterpiece of cognac blending, featuring eaux-de-vie aged up to 130 years from Grande Champagne.",
    type: "spirits",
    varietal: "Cognac",
    region: "Cognac, France",
    producer: "Hennessy",
    alcohol_content: 40.0,
    volume_ml: 700,
    base_price: 485,
    current_price: 510,
    price_change_24h: 5.2,
    fiveYearPriceChangePct: 38.9,
    slug: "hennessy-paradis",
    average_rating: 4.8,
    total_reviews: 124,
    primary_image_url: "/images/spirits/hennessy-paradis.jpg",
    image_urls: ["/images/spirits/hennessy-paradis.jpg"],
    tasting_notes: "Honey, dried fruits, spices with incredible smoothness and complexity from decades of aging.",
    food_pairings: ["Dark chocolate", "Cigars", "Aged cheese"],
    serving_temperature: "Room temperature, neat",
    aging_potential: "Ready to drink, will continue to evolve",
    vineyard_location: "Grande Champagne region of Cognac",
    estate_history: "Founded in 1765, world's largest cognac producer",
    production_methods: "Double distillation, aged in Limousin oak barrels",
    certifications: ["Cognac AOC", "Grande Champagne"],
    available_quantity: 9,
    minimum_order_quantity: 1,
    last_traded_price: 495,
    price_range_52week: { low: 465, high: 535 },
    seller: {
      id: "seller-spirits-1",
      business_name: "Rare Spirits International",
      seller_rating: 5.0,
      license_number: "TTB-JP-001122",
      license_state: "NY",
      verification_status: "verified",
      years_in_business: 22,
      total_sales: 892
    },
    requires_adult_signature: true,
    ttb_approved: true,
    created_at: new Date('2024-04-15'),
    updated_at: new Date('2024-06-20'),
    featured: false,
    rarity_score: 8.2,
    investment_grade: true
  },
  {
    id: "batch1-005",
    name: "Opus One 2018",
    description: "The legendary Napa Valley collaboration between Robert Mondavi and Baron Philippe de Rothschild.",
    type: "wine",
    varietal: "Cabernet Sauvignon Blend",
    region: "Oakville, Napa Valley",
    appellation: "Oakville AVA",
    vintage: 2018,
    producer: "Opus One",
    alcohol_content: 15.0,
    volume_ml: 750,
    base_price: 425,
    current_price: 445,
    price_change_24h: 4.7,
    fiveYearPriceChangePct: 52.1,
    slug: "opus-one-2018",
    average_rating: 4.7,
    total_reviews: 198,
    wine_spectator_score: 96,
    robert_parker_score: 95,
    james_suckling_score: 97,
    primary_image_url: "/images/wines/opus-one-2018.jpg",
    image_urls: ["/images/wines/opus-one-2018.jpg"],
    tasting_notes: "Blackcurrant, cedar, graphite with velvety tannins. Perfect marriage of Bordeaux elegance and Napa power.",
    food_pairings: ["Prime beef", "Lamb with herbs", "Aged hard cheeses"],
    serving_temperature: "62-67°F",
    aging_potential: "20-30 years",
    vineyard_location: "Oakville estate vineyard, Napa Valley",
    estate_history: "Founded in 1979 as Franco-American partnership",
    production_methods: "Hand-harvested, French oak aging, gravity-flow winery",
    certifications: ["Napa Valley AVA", "Estate Grown"],
    available_quantity: 15,
    minimum_order_quantity: 1,
    last_traded_price: 435,
    price_range_52week: { low: 405, high: 475 },
    seller: {
      id: "seller-napa-1",
      business_name: "Napa Valley Cult Wine Collective",
      seller_rating: 4.8,
      license_number: "TTB-CA-009876",
      license_state: "CA",
      verification_status: "verified",
      years_in_business: 18,
      total_sales: 2156
    },
    requires_adult_signature: true,
    ttb_approved: true,
    created_at: new Date('2024-04-20'),
    updated_at: new Date('2024-06-20'),
    featured: true,
    rarity_score: 8.7,
    investment_grade: true
  },
  {
    id: "batch1-006",
    name: "Hibiki 21 Year Old",
    description: "Japan's most harmonious whisky, blending over 20 malt and grain whiskies aged for at least 21 years.",
    type: "spirits",
    varietal: "Blended Japanese Whisky",
    region: "Japan",
    producer: "Suntory",
    alcohol_content: 43.0,
    volume_ml: 700,
    base_price: 2850,
    current_price: 2950,
    price_change_24h: 3.5,
    fiveYearPriceChangePct: 145.6,
    slug: "hibiki-21-year-old",
    average_rating: 4.9,
    total_reviews: 87,
    primary_image_url: "/images/spirits/hibiki-21.jpg",
    image_urls: ["/images/spirits/hibiki-21.jpg"],
    tasting_notes: "Honey, orange peel, white chocolate with incredible balance and harmony. The essence of Japanese whisky.",
    food_pairings: ["Sushi", "Dark chocolate", "Wagyu beef"],
    serving_temperature: "Room temperature or with ice",
    aging_potential: "Peak maturity reached",
    vineyard_location: "Yamazaki and Hakushu distilleries",
    estate_history: "Created in 1989 to represent the harmony of Japanese nature",
    production_methods: "Blend of malt and grain whiskies, Japanese oak influence",
    certifications: ["Japanese Whisky", "21 Year Age Statement"],
    available_quantity: 4,
    minimum_order_quantity: 1,
    last_traded_price: 2900,
    price_range_52week: { low: 2700, high: 3100 },
    seller: {
      id: "seller-spirits-1",
      business_name: "Rare Spirits International",
      seller_rating: 5.0,
      license_number: "TTB-JP-001122",
      license_state: "NY",
      verification_status: "verified",
      years_in_business: 22,
      total_sales: 892
    },
    requires_adult_signature: true,
    ttb_approved: true,
    created_at: new Date('2024-04-25'),
    updated_at: new Date('2024-06-20'),
    featured: true,
    rarity_score: 9.2,
    investment_grade: true
  },
  {
    id: "batch1-007",
    name: "Château d'Yquem 2015",
    description: "The world's greatest dessert wine, from the only Premier Cru Supérieur in Sauternes classification.",
    type: "wine",
    varietal: "Sémillon & Sauvignon Blanc",
    region: "Sauternes, Bordeaux",
    appellation: "Sauternes AOC",
    vintage: 2015,
    producer: "Château d'Yquem",
    alcohol_content: 14.0,
    volume_ml: 750,
    base_price: 385,
    current_price: 420,
    price_change_24h: 9.1,
    fiveYearPriceChangePct: 48.2,
    slug: "chateau-dyquem-2015",
    average_rating: 4.9,
    total_reviews: 76,
    wine_spectator_score: 98,
    robert_parker_score: 97,
    primary_image_url: "/images/wines/yquem-2015.jpg",
    image_urls: ["/images/wines/yquem-2015.jpg"],
    tasting_notes: "Apricot, honey, spice with perfect balance of sweetness and acidity. Liquid gold with centuries of history.",
    food_pairings: ["Foie gras", "Blue cheese", "Crème brûlée"],
    serving_temperature: "46-50°F",
    aging_potential: "50+ years",
    vineyard_location: "Sauternes, Left Bank Bordeaux",
    estate_history: "400+ year history, owned by LVMH since 1999",
    production_methods: "Hand-harvested botrytis-affected grapes, barrel fermentation",
    certifications: ["Sauternes AOC", "Premier Cru Supérieur"],
    available_quantity: 7,
    minimum_order_quantity: 1,
    last_traded_price: 405,
    price_range_52week: { low: 365, high: 450 },
    seller: {
      id: "seller-bordeaux-1",
      business_name: "Bordeaux Fine Wine Merchants",
      seller_rating: 4.9,
      license_number: "TTB-FR-001234",
      license_state: "CA",
      verification_status: "verified",
      years_in_business: 25,
      total_sales: 3847
    },
    requires_adult_signature: true,
    ttb_approved: true,
    created_at: new Date('2024-05-01'),
    updated_at: new Date('2024-06-20'),
    featured: false,
    rarity_score: 9.1,
    investment_grade: true
  },
  {
    id: "batch1-008",
    name: "Macallan 25 Year Old Sherry Oak",
    description: "The pinnacle of Macallan's sherry oak range, aged exclusively in hand-picked sherry seasoned oak casks.",
    type: "spirits",
    varietal: "Single Malt Scotch",
    region: "Speyside, Scotland",
    producer: "The Macallan",
    alcohol_content: 43.0,
    volume_ml: 700,
    base_price: 1850,
    current_price: 1950,
    price_change_24h: 5.4,
    fiveYearPriceChangePct: 87.3,
    slug: "macallan-25-year-old-sherry-oak",
    average_rating: 4.8,
    total_reviews: 145,
    primary_image_url: "/images/spirits/macallan-25.jpg",
    image_urls: ["/images/spirits/macallan-25.jpg"],
    tasting_notes: "Rich fruits, chocolate, spice with incredible depth from quarter-century sherry cask maturation.",
    food_pairings: ["Dark chocolate", "Stilton cheese", "Cigars"],
    serving_temperature: "Room temperature, neat",
    aging_potential: "Peak maturity reached",
    vineyard_location: "Easter Elchies House, Speyside",
    estate_history: "Founded in 1824, renowned for sherry cask maturation",
    production_methods: "Traditional pot still distillation, exclusive sherry casks",
    certifications: ["Single Malt Scotch", "25 Year Age Statement"],
    available_quantity: 5,
    minimum_order_quantity: 1,
    last_traded_price: 1900,
    price_range_52week: { low: 1750, high: 2050 },
    seller: {
      id: "seller-spirits-2",
      business_name: "Auction House Spirits",
      seller_rating: 5.0,
      license_number: "TTB-UK-003344",
      license_state: "NY",
      verification_status: "verified",
      years_in_business: 35,
      total_sales: 456
    },
    requires_adult_signature: true,
    ttb_approved: true,
    created_at: new Date('2024-05-05'),
    updated_at: new Date('2024-06-20'),
    featured: false,
    rarity_score: 8.9,
    investment_grade: true
  },
  {
    id: "batch1-009",
    name: "Caymus Cabernet Sauvignon 2020",
    description: "Napa Valley's most beloved Cabernet, known for its rich, approachable style and consistent quality.",
    type: "wine",
    varietal: "Cabernet Sauvignon",
    region: "Napa Valley, California",
    appellation: "Napa Valley AVA",
    vintage: 2020,
    producer: "Caymus Vineyards",
    alcohol_content: 14.8,
    volume_ml: 750,
    base_price: 89,
    current_price: 95,
    price_change_24h: 6.7,
    fiveYearPriceChangePct: 24.5,
    slug: "caymus-cabernet-sauvignon-2020",
    average_rating: 4.5,
    total_reviews: 324,
    wine_spectator_score: 92,
    james_suckling_score: 93,
    primary_image_url: "/images/wines/caymus-2020.jpg",
    image_urls: ["/images/wines/caymus-2020.jpg"],
    tasting_notes: "Blackberry, vanilla, cocoa with smooth tannins. Classic Napa Cabernet with broad appeal.",
    food_pairings: ["Grilled steak", "BBQ ribs", "Aged cheddar"],
    serving_temperature: "60-65°F",
    aging_potential: "8-12 years",
    vineyard_location: "Napa Valley estate vineyards",
    estate_history: "Family-owned since 1972, Wagner family legacy",
    production_methods: "Traditional winemaking, American oak aging",
    certifications: ["Napa Valley AVA", "Family Estate"],
    available_quantity: 24,
    minimum_order_quantity: 1,
    last_traded_price: 92,
    price_range_52week: { low: 85, high: 105 },
    seller: {
      id: "seller-napa-2",
      business_name: "California Wine Direct",
      seller_rating: 4.7,
      license_number: "TTB-CA-012345",
      license_state: "CA",
      verification_status: "verified",
      years_in_business: 12,
      total_sales: 4521
    },
    requires_adult_signature: true,
    ttb_approved: true,
    created_at: new Date('2024-05-10'),
    updated_at: new Date('2024-06-20'),
    featured: false,
    rarity_score: 6.5,
    investment_grade: false
  },
  {
    id: "batch1-010",
    name: "Glenfiddich 21 Year Old Gran Reserva",
    description: "Finished in Caribbean rum casks, this innovative Speyside single malt offers unique tropical complexity.",
    type: "spirits",
    varietal: "Single Malt Scotch",
    region: "Speyside, Scotland",
    producer: "Glenfiddich",
    alcohol_content: 40.0,
    volume_ml: 700,
    base_price: 195,
    current_price: 205,
    price_change_24h: 5.1,
    fiveYearPriceChangePct: 31.2,
    slug: "glenfiddich-21-year-old-gran-reserva",
    average_rating: 4.4,
    total_reviews: 267,
    primary_image_url: "/images/spirits/glenfiddich-21.jpg",
    image_urls: ["/images/spirits/glenfiddich-21.jpg"],
    tasting_notes: "Banana, toffee, spice with tropical fruit notes from rum cask finishing. Innovative and approachable.",
    food_pairings: ["Grilled pineapple", "Spiced desserts", "Mild cigars"],
    serving_temperature: "Room temperature or with ice",
    aging_potential: "Ready to drink",
    vineyard_location: "Dufftown, Speyside",
    estate_history: "Founded in 1887, family-owned William Grant & Sons",
    production_methods: "Traditional pot still, finished in Caribbean rum casks",
    certifications: ["Single Malt Scotch", "21 Year Age Statement"],
    available_quantity: 18,
    minimum_order_quantity: 1,
    last_traded_price: 200,
    price_range_52week: { low: 185, high: 220 },
    seller: {
      id: "seller-spirits-3",
      business_name: "Scotch Whisky Specialists",
      seller_rating: 4.6,
      license_number: "TTB-UK-004455",
      license_state: "TX",
      verification_status: "verified",
      years_in_business: 15,
      total_sales: 2134
    },
    requires_adult_signature: true,
    ttb_approved: true,
    created_at: new Date('2024-05-15'),
    updated_at: new Date('2024-06-20'),
    featured: false,
    rarity_score: 7.2,
    investment_grade: false
  },

  // === BATCH 2: ITALIAN WINES & PREMIUM SPIRITS ===
  {
    id: "batch2-001",
    name: "Barolo Monfortino Riserva 2014 - Giacomo Conterno",
    description: "The king of Italian wines from the legendary Giacomo Conterno estate, representing the pinnacle of traditional Barolo.",
    type: "wine",
    varietal: "Nebbiolo",
    region: "Piedmont, Italy",
    appellation: "Barolo DOCG",
    vintage: 2014,
    producer: "Giacomo Conterno",
    alcohol_content: 14.5,
    volume_ml: 750,
    base_price: 650,
    current_price: 685,
    price_change_24h: 5.4,
    fiveYearPriceChangePct: 58.3,
    slug: "barolo-monfortino-riserva-2014-giacomo-conterno",
    average_rating: 4.9,
    total_reviews: 78,
    wine_spectator_score: 97,
    robert_parker_score: 96,
    primary_image_url: "/images/wines/conterno-monfortino.jpg",
    image_urls: ["/images/wines/conterno-monfortino.jpg"],
    tasting_notes: "Rose petals, tar, cherry with massive structure and decades of aging potential. Traditional Barolo at its finest.",
    food_pairings: ["Truffle risotto", "Brasato al Barolo", "Aged Gorgonzola"],
    serving_temperature: "62-67°F",
    aging_potential: "30-50 years",
    vineyard_location: "Serralunga d'Alba, Piedmont",
    estate_history: "Founded in 1908, family estate known for traditional methods",
    production_methods: "Traditional long maceration, large Slavonian oak aging",
    certifications: ["Barolo DOCG", "Riserva"],
    available_quantity: 4,
    minimum_order_quantity: 1,
    last_traded_price: 670,
    price_range_52week: { low: 620, high: 720 },
    seller: {
      id: "seller-italy-1",
      business_name: "Italian Fine Wine Imports",
      seller_rating: 4.8,
      license_number: "TTB-IT-001234",
      license_state: "NY",
      verification_status: "verified",
      years_in_business: 18,
      total_sales: 1567
    },
    requires_adult_signature: true,
    ttb_approved: true,
    created_at: new Date('2024-05-20'),
    updated_at: new Date('2024-06-20'),
    featured: true,
    rarity_score: 9.3,
    investment_grade: true
  },
  {
    id: "batch2-002",
    name: "Brunello di Montalcino Riserva 2017 - Biondi Santi",
    description: "From the estate that created Brunello di Montalcino, this Riserva represents over 150 years of winemaking tradition.",
    type: "wine",
    varietal: "Sangiovese Grosso",
    region: "Tuscany, Italy",
    appellation: "Brunello di Montalcino DOCG",
    vintage: 2017,
    producer: "Biondi Santi",
    alcohol_content: 14.0,
    volume_ml: 750,
    base_price: 485,
    current_price: 520,
    price_change_24h: 7.2,
    fiveYearPriceChangePct: 72.1,
    slug: "brunello-di-montalcino-riserva-2017-biondi-santi",
    average_rating: 4.8,
    total_reviews: 94,
    wine_spectator_score: 95,
    robert_parker_score: 94,
    primary_image_url: "/images/wines/biondi-santi-brunello.jpg",
    image_urls: ["/images/wines/biondi-santi-brunello.jpg"],
    tasting_notes: "Cherry, leather, herbs with incredible elegance and longevity. The essence of Sangiovese Grosso.",
    food_pairings: ["Wild boar", "Pecorino Toscano", "Florentine steak"],
    serving_temperature: "60-65°F",
    aging_potential: "25-40 years",
    vineyard_location: "Il Greppo estate, Montalcino",
    estate_history: "Founded in 1840, creators of Brunello di Montalcino",
    production_methods: "Traditional methods, large Slavonian oak barrels",
    certifications: ["Brunello di Montalcino DOCG", "Riserva"],
    available_quantity: 6,
    minimum_order_quantity: 1,
    last_traded_price: 505,
    price_range_52week: { low: 465, high: 550 },
    seller: {
      id: "seller-italy-1",
      business_name: "Italian Fine Wine Imports",
      seller_rating: 4.8,
      license_number: "TTB-IT-001234",
      license_state: "NY",
      verification_status: "verified",
      years_in_business: 18,
      total_sales: 1567
    },
    requires_adult_signature: true,
    ttb_approved: true,
    created_at: new Date('2024-05-25'),
    updated_at: new Date('2024-06-20'),
    featured: false,
    rarity_score: 8.9,
    investment_grade: true
  },
  {
    id: "batch2-003",
    name: "Louis XIII Cognac",
    description: "The ultimate expression of cognac, blending up to 1,200 eaux-de-vie aged between 40 and 100 years.",
    type: "spirits",
    varietal: "Cognac",
    region: "Cognac, France",
    producer: "Rémy Martin",
    alcohol_content: 40.0,
    volume_ml: 700,
    base_price: 3850,
    current_price: 4050,
    price_change_24h: 5.2,
    fiveYearPriceChangePct: 95.7,
    slug: "louis-xiii-cognac",
    average_rating: 4.9,
    total_reviews: 67,
    primary_image_url: "/images/spirits/louis-xiii.jpg",
    image_urls: ["/images/spirits/louis-xiii.jpg"],
    tasting_notes: "Dried fruits, honey, spices with incredible complexity from century-old eaux-de-vie. Liquid history.",
    food_pairings: ["Cigars", "Dark chocolate", "Aged cheese"],
    serving_temperature: "Room temperature, neat",
    aging_potential: "Peak maturity reached",
    vineyard_location: "Grande Champagne region of Cognac",
    estate_history: "Founded in 1724, house of Rémy Martin",
    production_methods: "Double distillation, aged in Limousin oak tierçons",
    certifications: ["Cognac AOC", "Grande Champagne"],
    available_quantity: 3,
    minimum_order_quantity: 1,
    last_traded_price: 3950,
    price_range_52week: { low: 3650, high: 4250 },
    seller: {
      id: "seller-spirits-1",
      business_name: "Rare Spirits International",
      seller_rating: 5.0,
      license_number: "TTB-JP-001122",
      license_state: "NY",
      verification_status: "verified",
      years_in_business: 22,
      total_sales: 892
    },
    requires_adult_signature: true,
    ttb_approved: true,
    created_at: new Date('2024-06-01'),
    updated_at: new Date('2024-06-20'),
    featured: true,
    rarity_score: 9.8,
    investment_grade: true
  },
  {
    id: "batch2-004",
    name: "Château Le Pin 2016",
    description: "The tiny Right Bank estate producing some of Bordeaux's most expensive wines, pure Merlot perfection.",
    type: "wine",
    varietal: "Merlot",
    region: "Pomerol, Bordeaux",
    appellation: "Pomerol AOC",
    vintage: 2016,
    producer: "Château Le Pin",
    alcohol_content: 14.5,
    volume_ml: 750,
    base_price: 4250,
    current_price: 4485,
    price_change_24h: 5.5,
    fiveYearPriceChangePct: 118.7,
    slug: "chateau-le-pin-2016",
    average_rating: 4.9,
    total_reviews: 43,
    wine_spectator_score: 98,
    robert_parker_score: 97,
    primary_image_url: "/images/wines/le-pin-2016.jpg",
    image_urls: ["/images/wines/le-pin-2016.jpg"],
    tasting_notes: "Plum, chocolate, violets with incredible concentration and silky texture. Merlot at its most refined.",
    food_pairings: ["Duck breast", "Mushroom risotto", "Soft cheeses"],
    serving_temperature: "60-65°F",
    aging_potential: "20-35 years",
    vineyard_location: "2-hectare vineyard in Pomerol",
    estate_history: "Acquired by Thienpont family in 1979, boutique production",
    production_methods: "Hand-harvested, 100% new French oak",
    certifications: ["Pomerol AOC", "Estate Bottled"],
    available_quantity: 2,
    minimum_order_quantity: 1,
    last_traded_price: 4350,
    price_range_52week: { low: 4000, high: 4650 },
    seller: {
      id: "seller-bordeaux-1",
      business_name: "Bordeaux Fine Wine Merchants",
      seller_rating: 4.9,
      license_number: "TTB-FR-001234",
      license_state: "CA",
      verification_status: "verified",
      years_in_business: 25,
      total_sales: 3847
    },
    requires_adult_signature: true,
    ttb_approved: true,
    created_at: new Date('2024-06-05'),
    updated_at: new Date('2024-06-20'),
    featured: true,
    rarity_score: 9.9,
    investment_grade: true
  },
  {
    id: "batch2-005",
    name: "Karuizawa 1984 Single Cask #7975",
    description: "From the legendary closed Japanese distillery, this single cask represents the holy grail of Japanese whisky.",
    type: "spirits",
    varietal: "Single Malt Japanese Whisky",
    region: "Japan",
    producer: "Karuizawa",
    alcohol_content: 61.8,
    volume_ml: 700,
    base_price: 15000,
    current_price: 16250,
    price_change_24h: 8.3,
    fiveYearPriceChangePct: 287.5,
    slug: "karuizawa-1984-single-cask-7975",
    average_rating: 5.0,
    total_reviews: 21,
    primary_image_url: "/images/spirits/karuizawa-1984.jpg",
    image_urls: ["/images/spirits/karuizawa-1984.jpg"],
    tasting_notes: "Intense sherry influence, dried fruits, leather with incredible depth from nearly 30 years of aging.",
    food_pairings: ["Dark chocolate", "Aged cheese", "Cigars"],
    serving_temperature: "Room temperature, neat or with a drop of water",
    aging_potential: "Peak maturity reached",
    vineyard_location: "Karuizawa Distillery (closed 2000)",
    estate_history: "Founded in 1955, closed in 2000, cult status among collectors",
    production_methods: "Single cask, sherry butt maturation",
    certifications: ["Single Malt Japanese Whisky", "Single Cask"],
    available_quantity: 1,
    minimum_order_quantity: 1,
    last_traded_price: 15800,
    price_range_52week: { low: 14500, high: 17000 },
    seller: {
      id: "seller-spirits-1",
      business_name: "Rare Spirits International",
      seller_rating: 5.0,
      license_number: "TTB-JP-001122",
      license_state: "NY",
      verification_status: "verified",
      years_in_business: 22,
      total_sales: 892
    },
    requires_adult_signature: true,
    ttb_approved: true,
    created_at: new Date('2024-06-10'),
    updated_at: new Date('2024-06-20'),
    featured: true,
    rarity_score: 10.0,
    investment_grade: true
  },
  {
    id: "batch2-006",
    name: "Sassicaia 2018",
    description: "The wine that started the Super Tuscan revolution, Cabernet Sauvignon and Cabernet Franc from Bolgheri.",
    type: "wine",
    varietal: "Cabernet Sauvignon & Cabernet Franc",
    region: "Tuscany, Italy",
    appellation: "Bolgheri Sassicaia DOC",
    vintage: 2018,
    producer: "Tenuta San Guido",
    alcohol_content: 14.0,
    volume_ml: 750,
    base_price: 285,
    current_price: 305,
    price_change_24h: 7.0,
    fiveYearPriceChangePct: 46.8,
    slug: "sassicaia-2018",
    average_rating: 4.7,
    total_reviews: 187,
    wine_spectator_score: 94,
    robert_parker_score: 93,
    james_suckling_score: 96,
    primary_image_url: "/images/wines/sassicaia-2018.jpg",
    image_urls: ["/images/wines/sassicaia-2018.jpg"],
    tasting_notes: "Blackcurrant, cedar, graphite with elegant tannins. The original Super Tuscan showing Bordeaux influence.",
    food_pairings: ["Grilled lamb", "Wild boar", "Aged Pecorino"],
    serving_temperature: "60-65°F",
    aging_potential: "15-25 years",
    vineyard_location: "Bolgheri estate, Tuscany coast",
    estate_history: "Created in 1968 by Marchese Mario Incisa della Rocchetta",
    production_methods: "French oak aging, Bordeaux-style winemaking",
    certifications: ["Bolgheri Sassicaia DOC", "Estate Grown"],
    available_quantity: 15,
    minimum_order_quantity: 1,
    last_traded_price: 295,
    price_range_52week: { low: 275, high: 325 },
    seller: {
      id: "seller-italy-1",
      business_name: "Italian Fine Wine Imports",
      seller_rating: 4.8,
      license_number: "TTB-IT-001234",
      license_state: "NY",
      verification_status: "verified",
      years_in_business: 18,
      total_sales: 1567
    },
    requires_adult_signature: true,
    ttb_approved: true,
    created_at: new Date('2024-06-15'),
    updated_at: new Date('2024-06-20'),
    featured: false,
    rarity_score: 8.4,
    investment_grade: true
  },
  {
    id: "batch2-007",
    name: "Johnnie Walker Blue Label Ghost and Rare Glenury Royal",
    description: "Ultra-rare blend featuring whisky from the closed Glenury Royal distillery, a collector's dream.",
    type: "spirits",
    varietal: "Blended Scotch Whisky",
    region: "Scotland",
    producer: "Johnnie Walker",
    alcohol_content: 43.8,
    volume_ml: 700,
    base_price: 1250,
    current_price: 1325,
    price_change_24h: 6.0,
    fiveYearPriceChangePct: 89.3,
    slug: "johnnie-walker-blue-label-ghost-rare-glenury-royal",
    average_rating: 4.6,
    total_reviews: 112,
    primary_image_url: "/images/spirits/jw-ghost-rare.jpg",
    image_urls: ["/images/spirits/jw-ghost-rare.jpg"],
    tasting_notes: "Honey, smoke, dried fruits with incredible complexity from rare closed distillery whiskies.",
    food_pairings: ["Smoked salmon", "Dark chocolate", "Highland cheese"],
    serving_temperature: "Room temperature or with ice",
    aging_potential: "Ready to drink",
    vineyard_location: "Various Scottish distilleries including closed Glenury Royal",
    estate_history: "Johnnie Walker established 1820, Ghost and Rare series launched 2019",
    production_methods: "Blend of rare and closed distillery whiskies",
    certifications: ["Scotch Whisky", "Limited Edition"],
    available_quantity: 8,
    minimum_order_quantity: 1,
    last_traded_price: 1285,
    price_range_52week: { low: 1200, high: 1400 },
    seller: {
      id: "seller-spirits-3",
      business_name: "Scotch Whisky Specialists",
      seller_rating: 4.6,
      license_number: "TTB-UK-004455",
      license_state: "TX",
      verification_status: "verified",
      years_in_business: 15,
      total_sales: 2134
    },
    requires_adult_signature: true,
    ttb_approved: true,
    created_at: new Date('2024-06-18'),
    updated_at: new Date('2024-06-20'),
    featured: false,
    rarity_score: 8.7,
    investment_grade: true
  },
  {
    id: "batch2-008",
    name: "Château Margaux 2010",
    description: "The most elegant of the First Growths, this legendary vintage showcases Margaux's perfect terroir expression.",
    type: "wine",
    varietal: "Cabernet Sauvignon Blend",
    region: "Margaux, Bordeaux",
    appellation: "Margaux AOC",
    vintage: 2010,
    producer: "Château Margaux",
    alcohol_content: 13.5,
    volume_ml: 750,
    base_price: 1150,
    current_price: 1225,
    price_change_24h: 6.5,
    fiveYearPriceChangePct: 67.8,
    slug: "chateau-margaux-2010",
    average_rating: 4.9,
    total_reviews: 98,
    wine_spectator_score: 99,
    robert_parker_score: 98,
    primary_image_url: "/images/wines/margaux-2010.jpg",
    image_urls: ["/images/wines/margaux-2010.jpg"],
    tasting_notes: "Violets, blackcurrant, cedar with incredible elegance and finesse. The essence of Margaux terroir.",
    food_pairings: ["Rack of lamb", "Duck breast", "Aged Roquefort"],
    serving_temperature: "60-65°F",
    aging_potential: "30-50 years",
    vineyard_location: "Margaux appellation, Left Bank Bordeaux",
    estate_history: "Historic château dating back to the 12th century",
    production_methods: "Traditional Bordeaux methods, new French oak",
    certifications: ["Margaux AOC", "First Growth"],
    available_quantity: 5,
    minimum_order_quantity: 1,
    last_traded_price: 1185,
    price_range_52week: { low: 1100, high: 1300 },
    seller: {
      id: "seller-bordeaux-1",
      business_name: "Bordeaux Fine Wine Merchants",
      seller_rating: 4.9,
      license_number: "TTB-FR-001234",
      license_state: "CA",
      verification_status: "verified",
      years_in_business: 25,
      total_sales: 3847
    },
    requires_adult_signature: true,
    ttb_approved: true,
    created_at: new Date('2024-06-12'),
    updated_at: new Date('2024-06-20'),
    featured: true,
    rarity_score: 9.7,
    investment_grade: true
  },
  {
    id: "batch2-009",
    name: "Ornellaia 2019",
    description: "Super Tuscan excellence from Bolgheri, rivaling the greatest Bordeaux with Italian flair and elegance.",
    type: "wine",
    varietal: "Cabernet Sauvignon, Merlot, Petit Verdot & Cabernet Franc",
    region: "Tuscany, Italy",
    appellation: "Bolgheri Superiore DOC",
    vintage: 2019,
    producer: "Ornellaia",
    alcohol_content: 14.5,
    volume_ml: 750,
    base_price: 385,
    current_price: 415,
    price_change_24h: 7.8,
    fiveYearPriceChangePct: 54.2,
    slug: "ornellaia-2019",
    average_rating: 4.8,
    total_reviews: 134,
    wine_spectator_score: 96,
    robert_parker_score: 95,
    james_suckling_score: 97,
    primary_image_url: "/images/wines/ornellaia-2019.jpg",
    image_urls: ["/images/wines/ornellaia-2019.jpg"],
    tasting_notes: "Blackberry, spice, tobacco with velvety tannins. Bordeaux-style elegance with Tuscan character.",
    food_pairings: ["Bistecca alla Fiorentina", "Wild boar ragu", "Aged Pecorino"],
    serving_temperature: "62-67°F",
    aging_potential: "15-25 years",
    vineyard_location: "Bolgheri estate, Tuscany coast",
    estate_history: "Founded in 1981 by Marchese Lodovico Antinori",
    production_methods: "French oak aging, Bordeaux-style winemaking",
    certifications: ["Bolgheri Superiore DOC", "Estate Grown"],
    available_quantity: 12,
    minimum_order_quantity: 1,
    last_traded_price: 405,
    price_range_52week: { low: 365, high: 445 },
    seller: {
      id: "seller-italy-1",
      business_name: "Italian Fine Wine Imports",
      seller_rating: 4.8,
      license_number: "TTB-IT-001234",
      license_state: "NY",
      verification_status: "verified",
      years_in_business: 18,
      total_sales: 1567
    },
    requires_adult_signature: true,
    ttb_approved: true,
    created_at: new Date('2024-06-08'),
    updated_at: new Date('2024-06-20'),
    featured: false,
    rarity_score: 8.6,
    investment_grade: true
  },
  {
    id: "batch2-010",
    name: "Balvenie 50 Year Old",
    description: "Half a century of maturation in a single cask, representing the pinnacle of Speyside single malt craftsmanship.",
    type: "spirits",
    varietal: "Single Malt Scotch",
    region: "Speyside, Scotland",
    producer: "The Balvenie",
    alcohol_content: 44.1,
    volume_ml: 700,
    base_price: 38500,
    current_price: 41250,
    price_change_24h: 7.1,
    fiveYearPriceChangePct: 156.2,
    slug: "balvenie-50-year-old",
    average_rating: 5.0,
    total_reviews: 18,
    primary_image_url: "/images/spirits/balvenie-50.jpg",
    image_urls: ["/images/spirits/balvenie-50.jpg"],
    tasting_notes: "Dried fruits, honey, oak with incredible depth and complexity from five decades of maturation.",
    food_pairings: ["Dark chocolate truffles", "Aged Stilton", "Premium cigars"],
    serving_temperature: "Room temperature, neat",
    aging_potential: "Peak maturity reached",
    vineyard_location: "Dufftown, Speyside",
    estate_history: "Founded in 1892, family-owned William Grant & Sons",
    production_methods: "Traditional pot still, single cask maturation",
    certifications: ["Single Malt Scotch", "50 Year Age Statement"],
    available_quantity: 1,
    minimum_order_quantity: 1,
    last_traded_price: 39800,
    price_range_52week: { low: 37000, high: 43000 },
    seller: {
      id: "seller-spirits-2",
      business_name: "Auction House Spirits",
      seller_rating: 5.0,
      license_number: "TTB-UK-003344",
      license_state: "NY",
      verification_status: "verified",
      years_in_business: 35,
      total_sales: 456
    },
    requires_adult_signature: true,
    ttb_approved: true,
    created_at: new Date('2024-06-22'),
    updated_at: new Date('2024-06-20'),
    featured: true,
    rarity_score: 10.0,
    investment_grade: true
  },

  // === BATCH 3: RHÔNE, CALIFORNIA & RARE SPIRITS ===
  {
    id: "batch3-001",
    name: "Hermitage La Chapelle 2016 - Paul Jaboulet Aîné",
    description: "The legendary hill of Hermitage produces some of the world's greatest Syrah, this vintage showing exceptional power and elegance.",
    type: "wine",
    varietal: "Syrah",
    region: "Hermitage, Rhône Valley",
    appellation: "Hermitage AOC",
    vintage: 2016,
    producer: "Paul Jaboulet Aîné",
    alcohol_content: 14.5,
    volume_ml: 750,
    base_price: 385,
    current_price: 415,
    price_change_24h: 7.8,
    fiveYearPriceChangePct: 56.3,
    slug: "hermitage-la-chapelle-2016-paul-jaboulet-aine",
    average_rating: 4.8,
    total_reviews: 89,
    wine_spectator_score: 96,
    robert_parker_score: 95,
    primary_image_url: "/images/wines/hermitage-la-chapelle.jpg",
    image_urls: ["/images/wines/hermitage-la-chapelle.jpg"],
    tasting_notes: "Blackberry, olive, pepper with massive structure and incredible aging potential. Pure Hermitage terroir.",
    food_pairings: ["Côte de boeuf", "Wild game", "Aged Roquefort"],
    serving_temperature: "62-67°F",
    aging_potential: "25-40 years",
    vineyard_location: "Hermitage hill, Northern Rhône",
    estate_history: "Founded in 1834, historic Rhône Valley producer",
    production_methods: "Traditional Rhône methods, large oak foudres",
    certifications: ["Hermitage AOC", "Estate Grown"],
    available_quantity: 8,
    minimum_order_quantity: 1,
    last_traded_price: 405,
    price_range_52week: { low: 365, high: 445 },
    seller: {
      id: "seller-rhone-1",
      business_name: "Rhône Valley Specialists",
      seller_rating: 4.7,
      license_number: "TTB-FR-006789",
      license_state: "CA",
      verification_status: "verified",
      years_in_business: 16,
      total_sales: 2234
    },
    requires_adult_signature: true,
    ttb_approved: true,
    created_at: new Date('2024-06-25'),
    updated_at: new Date('2024-06-30'),
    featured: false,
    rarity_score: 8.7,
    investment_grade: true
  },
  {
    id: "batch3-002",
    name: "Harlan Estate 2019",
    description: "Napa Valley's most exclusive estate, producing wines of legendary status from Oakville hillside vineyards.",
    type: "wine",
    varietal: "Cabernet Sauvignon Blend",
    region: "Oakville, Napa Valley",
    appellation: "Oakville AVA",
    vintage: 2019,
    producer: "Harlan Estate",
    alcohol_content: 15.2,
    volume_ml: 750,
    base_price: 1850,
    current_price: 1950,
    price_change_24h: 5.4,
    fiveYearPriceChangePct: 89.7,
    slug: "harlan-estate-2019",
    average_rating: 4.9,
    total_reviews: 67,
    wine_spectator_score: 98,
    robert_parker_score: 97,
    james_suckling_score: 99,
    primary_image_url: "/images/wines/harlan-estate-2019.jpg",
    image_urls: ["/images/wines/harlan-estate-2019.jpg"],
    tasting_notes: "Blackcurrant, cedar, graphite with incredible concentration and finesse. Napa Valley at its pinnacle.",
    food_pairings: ["Prime ribeye", "Venison", "Aged Stilton"],
    serving_temperature: "62-67°F",
    aging_potential: "25-40 years",
    vineyard_location: "Oakville hillside estate",
    estate_history: "Founded in 1984 by Bill Harlan, cult status producer",
    production_methods: "Biodynamic farming, gravity-flow winery",
    certifications: ["Napa Valley AVA", "Estate Grown"],
    available_quantity: 3,
    minimum_order_quantity: 1,
    last_traded_price: 1900,
    price_range_52week: { low: 1750, high: 2100 },
    seller: {
      id: "seller-napa-1",
      business_name: "Napa Valley Cult Wine Collective",
      seller_rating: 4.8,
      license_number: "TTB-CA-009876",
      license_state: "CA",
      verification_status: "verified",
      years_in_business: 18,
      total_sales: 2156
    },
    requires_adult_signature: true,
    ttb_approved: true,
    created_at: new Date('2024-06-28'),
    updated_at: new Date('2024-06-30'),
    featured: true,
    rarity_score: 9.6,
    investment_grade: true
  },
  {
    id: "batch3-003",
    name: "Macallan Exceptional Single Cask 1950",
    description: "The oldest Macallan ever released, distilled in 1950 and aged for 67 years in a single sherry hogshead.",
    type: "spirits",
    varietal: "Single Malt Scotch",
    region: "Speyside, Scotland",
    producer: "The Macallan",
    alcohol_content: 42.8,
    volume_ml: 700,
    base_price: 125000,
    current_price: 135000,
    price_change_24h: 8.0,
    fiveYearPriceChangePct: 487.3,
    slug: "macallan-exceptional-single-cask-1950",
    average_rating: 5.0,
    total_reviews: 9,
    primary_image_url: "/images/spirits/macallan-1950.jpg",
    image_urls: ["/images/spirits/macallan-1950.jpg"],
    tasting_notes: "Dried fruits, leather, antique oak with layers of complexity from 67 years of maturation.",
    food_pairings: ["Dark chocolate truffles", "Aged cheese", "Premium cigars"],
    serving_temperature: "Room temperature, neat",
    aging_potential: "Peak maturity reached",
    vineyard_location: "Easter Elchies House, Speyside",
    estate_history: "Founded in 1824, renowned for exceptional single casks",
    production_methods: "Single cask, sherry hogshead maturation",
    certifications: ["Single Malt Scotch", "Single Cask"],
    available_quantity: 1,
    minimum_order_quantity: 1,
    last_traded_price: 130000,
    price_range_52week: { low: 120000, high: 140000 },
    seller: {
      id: "seller-spirits-2",
      business_name: "Auction House Spirits",
      seller_rating: 5.0,
      license_number: "TTB-UK-003344",
      license_state: "NY",
      verification_status: "verified",
      years_in_business: 35,
      total_sales: 456
    },
    requires_adult_signature: true,
    ttb_approved: true,
    created_at: new Date('2024-07-01'),
    updated_at: new Date('2024-07-01'),
    featured: true,
    rarity_score: 10.0,
    investment_grade: true
  },
  {
    id: "batch3-004",
    name: "Tignanello 2019",
    description: "The wine that revolutionized Italian winemaking, blending Sangiovese with international varieties.",
    type: "wine",
    varietal: "Sangiovese, Cabernet Sauvignon & Cabernet Franc",
    region: "Tuscany, Italy",
    appellation: "Toscana IGT",
    vintage: 2019,
    producer: "Antinori",
    alcohol_content: 14.0,
    volume_ml: 750,
    base_price: 125,
    current_price: 135,
    price_change_24h: 8.0,
    fiveYearPriceChangePct: 35.2,
    slug: "tignanello-2019",
    average_rating: 4.6,
    total_reviews: 245,
    wine_spectator_score: 94,
    robert_parker_score: 93,
    james_suckling_score: 95,
    primary_image_url: "/images/wines/tignanello-2019.jpg",
    image_urls: ["/images/wines/tignanello-2019.jpg"],
    tasting_notes: "Cherry, spice, tobacco with elegant tannins. The perfect marriage of tradition and innovation.",
    food_pairings: ["Tuscan steak", "Wild boar", "Aged Pecorino"],
    serving_temperature: "60-65°F",
    aging_potential: "12-18 years",
    vineyard_location: "Tignanello vineyard, Chianti Classico",
    estate_history: "Antinori family, 26 generations of winemaking",
    production_methods: "French oak aging, innovative winemaking",
    certifications: ["Toscana IGT", "Estate Grown"],
    available_quantity: 18,
    minimum_order_quantity: 1,
    last_traded_price: 130,
    price_range_52week: { low: 115, high: 145 },
    seller: {
      id: "seller-italy-1",
      business_name: "Italian Fine Wine Imports",
      seller_rating: 4.8,
      license_number: "TTB-IT-001234",
      license_state: "NY",
      verification_status: "verified",
      years_in_business: 18,
      total_sales: 1567
    },
    requires_adult_signature: true,
    ttb_approved: true,
    created_at: new Date('2024-07-03'),
    updated_at: new Date('2024-07-05'),
    featured: false,
    rarity_score: 7.8,
    investment_grade: false
  },
  {
    id: "batch3-005",
    name: "Remy Martin XO Excellence",
    description: "The original XO cognac, blending eaux-de-vie aged between 10 and 37 years for exceptional complexity.",
    type: "spirits",
    varietal: "Cognac",
    region: "Cognac, France",
    producer: "Rémy Martin",
    alcohol_content: 40.0,
    volume_ml: 700,
    base_price: 285,
    current_price: 305,
    price_change_24h: 7.0,
    fiveYearPriceChangePct: 42.1,
    slug: "remy-martin-xo-excellence",
    average_rating: 4.7,
    total_reviews: 189,
    primary_image_url: "/images/spirits/remy-martin-xo.jpg",
    image_urls: ["/images/spirits/remy-martin-xo.jpg"],
    tasting_notes: "Dried fruits, honey, spices with incredible smoothness and length. The benchmark XO cognac.",
    food_pairings: ["Dark chocolate", "Cigars", "Aged cheese"],
    serving_temperature: "Room temperature, neat",
    aging_potential: "Ready to drink",
    vineyard_location: "Grande and Petite Champagne regions",
    estate_history: "Founded in 1724, creators of XO category",
    production_methods: "Double distillation, Limousin oak aging",
    certifications: ["Cognac AOC", "XO"],
    available_quantity: 15,
    minimum_order_quantity: 1,
    last_traded_price: 295,
    price_range_52week: { low: 275, high: 325 },
    seller: {
      id: "seller-spirits-1",
      business_name: "Rare Spirits International",
      seller_rating: 5.0,
      license_number: "TTB-JP-001122",
      license_state: "NY",
      verification_status: "verified",
      years_in_business: 22,
      total_sales: 892
    },
    requires_adult_signature: true,
    ttb_approved: true,
    created_at: new Date('2024-07-05'),
    updated_at: new Date('2024-07-05'),
    featured: false,
    rarity_score: 7.5,
    investment_grade: false
  },
  {
    id: "batch3-006",
    name: "Château Pichon Baron 2016",
    description: "Second Growth Pauillac showing incredible power and elegance, a modern classic from a legendary vintage.",
    type: "wine",
    varietal: "Cabernet Sauvignon Blend",
    region: "Pauillac, Bordeaux",
    appellation: "Pauillac AOC",
    vintage: 2016,
    producer: "Château Pichon Baron",
    alcohol_content: 14.0,
    volume_ml: 750,
    base_price: 185,
    current_price: 205,
    price_change_24h: 10.8,
    fiveYearPriceChangePct: 67.2,
    slug: "chateau-pichon-baron-2016",
    average_rating: 4.7,
    total_reviews: 134,
    wine_spectator_score: 95,
    robert_parker_score: 94,
    primary_image_url: "/images/wines/pichon-baron-2016.jpg",
    image_urls: ["/images/wines/pichon-baron-2016.jpg"],
    tasting_notes: "Cassis, cedar, graphite with powerful tannins and incredible length. Classic Pauillac structure.",
    food_pairings: ["Rack of lamb", "Beef Wellington", "Aged Comté"],
    serving_temperature: "60-65°F",
    aging_potential: "20-30 years",
    vineyard_location: "Pauillac, Left Bank Bordeaux",
    estate_history: "Founded in 1694, Second Growth since 1855",
    production_methods: "Traditional Bordeaux methods, French oak",
    certifications: ["Pauillac AOC", "Second Growth"],
    available_quantity: 12,
    minimum_order_quantity: 1,
    last_traded_price: 195,
    price_range_52week: { low: 175, high: 220 },
    seller: {
      id: "seller-bordeaux-1",
      business_name: "Bordeaux Fine Wine Merchants",
      seller_rating: 4.9,
      license_number: "TTB-FR-001234",
      license_state: "CA",
      verification_status: "verified",
      years_in_business: 25,
      total_sales: 3847
    },
    requires_adult_signature: true,
    ttb_approved: true,
    created_at: new Date('2024-07-08'),
    updated_at: new Date('2024-07-10'),
    featured: false,
    rarity_score: 8.3,
    investment_grade: true
  },
  {
    id: "batch3-007",
    name: "Bowmore 1964 Black Bowmore",
    description: "The legendary Black Bowmore, one of the most sought-after Islay single malts ever produced.",
    type: "spirits",
    varietal: "Single Malt Scotch",
    region: "Islay, Scotland",
    producer: "Bowmore",
    alcohol_content: 50.0,
    volume_ml: 750,
    base_price: 28500,
    current_price: 31250,
    price_change_24h: 9.6,
    fiveYearPriceChangePct: 234.8,
    slug: "bowmore-1964-black-bowmore",
    average_rating: 5.0,
    total_reviews: 23,
    primary_image_url: "/images/spirits/black-bowmore.jpg",
    image_urls: ["/images/spirits/black-bowmore.jpg"],
    tasting_notes: "Peat smoke, sea salt, dried fruits with incredible complexity from decades of Islay maturation.",
    food_pairings: ["Smoked salmon", "Dark chocolate", "Aged cheese"],
    serving_temperature: "Room temperature, neat or with a drop of water",
    aging_potential: "Peak maturity reached",
    vineyard_location: "Bowmore Distillery, Islay",
    estate_history: "Founded in 1779, oldest distillery on Islay",
    production_methods: "Traditional pot still, sherry cask maturation",
    certifications: ["Single Malt Scotch", "Vintage 1964"],
    available_quantity: 1,
    minimum_order_quantity: 1,
    last_traded_price: 29800,
    price_range_52week: { low: 27000, high: 33000 },
    seller: {
      id: "seller-spirits-3",
      business_name: "Scotch Whisky Specialists",
      seller_rating: 4.6,
      license_number: "TTB-UK-004455",
      license_state: "TX",
      verification_status: "verified",
      years_in_business: 15,
      total_sales: 2134
    },
    requires_adult_signature: true,
    ttb_approved: true,
    created_at: new Date('2024-07-10'),
    updated_at: new Date('2024-07-10'),
    featured: true,
    rarity_score: 9.9,
    investment_grade: true
  },
  {
    id: "batch3-008",
    name: "Solaia 2018",
    description: "Antinori's flagship Super Tuscan, rivaling the greatest Bordeaux with pure Tuscan elegance.",
    type: "wine",
    varietal: "Cabernet Sauvignon, Sangiovese & Cabernet Franc",
    region: "Tuscany, Italy",
    appellation: "Toscana IGT",
    vintage: 2018,
    producer: "Antinori",
    alcohol_content: 14.5,
    volume_ml: 750,
    base_price: 285,
    current_price: 315,
    price_change_24h: 10.5,
    fiveYearPriceChangePct: 78.4,
    slug: "solaia-2018",
    average_rating: 4.8,
    total_reviews: 156,
    wine_spectator_score: 96,
    robert_parker_score: 95,
    james_suckling_score: 97,
    primary_image_url: "/images/wines/solaia-2018.jpg",
    image_urls: ["/images/wines/solaia-2018.jpg"],
    tasting_notes: "Blackcurrant, spice, tobacco with velvety tannins. Bordeaux-style power with Tuscan soul.",
    food_pairings: ["Bistecca alla Fiorentina", "Wild boar", "Aged Pecorino"],
    serving_temperature: "62-67°F",
    aging_potential: "18-25 years",
    vineyard_location: "Solaia vineyard, Chianti Classico",
    estate_history: "Antinori family, 26 generations of winemaking excellence",
    production_methods: "French oak aging, Bordeaux-style winemaking",
    certifications: ["Toscana IGT", "Estate Grown"],
    available_quantity: 10,
    minimum_order_quantity: 1,
    last_traded_price: 305,
    price_range_52week: { low: 275, high: 335 },
    seller: {
      id: "seller-italy-1",
      business_name: "Italian Fine Wine Imports",
      seller_rating: 4.8,
      license_number: "TTB-IT-001234",
      license_state: "NY",
      verification_status: "verified",
      years_in_business: 18,
      total_sales: 1567
    },
    requires_adult_signature: true,
    ttb_approved: true,
    created_at: new Date('2024-07-12'),
    updated_at: new Date('2024-07-12'),
    featured: false,
    rarity_score: 8.6,
    investment_grade: true
  },
  {
    id: "batch3-009",
    name: "Silver Oak Alexander Valley Cabernet Sauvignon 2017",
    description: "California's most distinctive Cabernet, aged exclusively in American oak for a unique flavor profile.",
    type: "wine",
    varietal: "Cabernet Sauvignon",
    region: "Alexander Valley, Sonoma",
    appellation: "Alexander Valley AVA",
    vintage: 2017,
    producer: "Silver Oak Cellars",
    alcohol_content: 14.8,
    volume_ml: 750,
    base_price: 125,
    current_price: 135,
    price_change_24h: 8.0,
    fiveYearPriceChangePct: 28.6,
    slug: "silver-oak-alexander-valley-cabernet-sauvignon-2017",
    average_rating: 4.5,
    total_reviews: 298,
    wine_spectator_score: 92,
    james_suckling_score: 93,
    primary_image_url: "/images/wines/silver-oak-2017.jpg",
    image_urls: ["/images/wines/silver-oak-2017.jpg"],
    tasting_notes: "Blackberry, vanilla, coconut with distinctive American oak influence. Uniquely Californian style.",
    food_pairings: ["BBQ ribs", "Grilled portobello", "Aged cheddar"],
    serving_temperature: "60-65°F",
    aging_potential: "10-15 years",
    vineyard_location: "Alexander Valley, Sonoma County",
    estate_history: "Founded in 1972, pioneers of American oak aging",
    production_methods: "Exclusively American oak barrels, extended aging",
    certifications: ["Alexander Valley AVA", "Estate Grown"],
    available_quantity: 20,
    minimum_order_quantity: 1,
    last_traded_price: 130,
    price_range_52week: { low: 115, high: 145 },
    seller: {
      id: "seller-sonoma-1",
      business_name: "Sonoma Wine Collective",
      seller_rating: 4.6,
      license_number: "TTB-CA-013456",
      license_state: "CA",
      verification_status: "verified",
      years_in_business: 14,
      total_sales: 3245
    },
    requires_adult_signature: true,
    ttb_approved: true,
    created_at: new Date('2024-07-15'),
    updated_at: new Date('2024-07-15'),
    featured: false,
    rarity_score: 6.8,
    investment_grade: false
  },
  {
    id: "batch3-010",
    name: "Johnnie Walker Blue Label",
    description: "The pinnacle of Johnnie Walker blending, featuring rare whiskies from closed distilleries.",
    type: "spirits",
    varietal: "Blended Scotch Whisky",
    region: "Scotland",
    producer: "Johnnie Walker",
    alcohol_content: 40.0,
    volume_ml: 750,
    base_price: 185,
    current_price: 195,
    price_change_24h: 5.4,
    fiveYearPriceChangePct: 34.5,
    slug: "johnnie-walker-blue-label",
    average_rating: 4.4,
    total_reviews: 567,
    primary_image_url: "/images/spirits/jw-blue-label.jpg",
    image_urls: ["/images/spirits/jw-blue-label.jpg"],
    tasting_notes: "Honey, smoke, dried fruits with incredible smoothness and complexity from rare whiskies.",
    food_pairings: ["Dark chocolate", "Smoked salmon", "Highland cheese"],
    serving_temperature: "Room temperature or with ice",
    aging_potential: "Ready to drink",
    vineyard_location: "Various Scottish distilleries",
    estate_history: "Johnnie Walker established 1820, Blue Label launched 1992",
    production_methods: "Blend of rare and aged whiskies",
    certifications: ["Scotch Whisky", "Premium Blend"],
    available_quantity: 25,
    minimum_order_quantity: 1,
    last_traded_price: 190,
    price_range_52week: { low: 175, high: 205 },
    seller: {
      id: "seller-spirits-3",
      business_name: "Scotch Whisky Specialists",
      seller_rating: 4.6,
      license_number: "TTB-UK-004455",
      license_state: "TX",
      verification_status: "verified",
      years_in_business: 15,
      total_sales: 2134
    },
    requires_adult_signature: true,
    ttb_approved: true,
    created_at: new Date('2024-07-18'),
    updated_at: new Date('2024-07-18'),
    featured: false,
    rarity_score: 7.0,
    investment_grade: false
  }
];

// Helper functions for product data
export const getProductById = (id: string): Product | undefined => {
  return products.find(product => product.id === id);
};

export const getProductsByType = (type: 'wine' | 'spirits'): Product[] => {
  return products.filter(product => product.type === type);
};

export const getFeaturedProducts = (): Product[] => {
  return products.filter(product => product.featured === true);
};

export const getInvestmentGradeProducts = (): Product[] => {
  return products.filter(product => product.investment_grade === true);
};

export const searchProducts = (query: string): Product[] => {
  const searchTerm = query.toLowerCase();
  return products.filter(product => 
    product.name.toLowerCase().includes(searchTerm) ||
    product.producer.toLowerCase().includes(searchTerm) ||
    product.region.toLowerCase().includes(searchTerm) ||
    product.varietal.toLowerCase().includes(searchTerm)
  );
}; 