import type { Product } from './api';

export const products: Product[] = [
  {
    "id": "65b69384-5c21-4f17-b4cc-66a4c526178c",
    "name": "Ch\u00e2teau Lafite Rothschild 2010",
    "category": "wine",
    "subCategory": "Bordeaux First Growth",
    "region": "Pauillac, Bordeaux, France",
    "producer": "Ch\u00e2teau Lafite Rothschild",
    "vintage": 2010.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 1255,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Blackcurrant, cedar, graphite, long finish.",
    "image": NaN,
    "slug": "ch-teau-lafite-rothschild-2010"
  },
  {
    "id": "b86b486f-9514-4fb5-a024-48572d1e5fcc",
    "name": "Ch\u00e2teau Mouton Rothschild 2016",
    "category": "wine",
    "subCategory": "Bordeaux First Growth",
    "region": "Pauillac, Bordeaux, France",
    "producer": "Ch\u00e2teau Mouton Rothschild",
    "vintage": 2016.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 850,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Cassis, tobacco leaf, opulent texture.",
    "image": NaN,
    "slug": "ch-teau-mouton-rothschild-2016"
  },
  {
    "id": "fa71e961-00cb-4aa3-99e0-6e3e2ec42915",
    "name": "Ch\u00e2teau Margaux 2015",
    "category": "wine",
    "subCategory": "Bordeaux First Growth",
    "region": "Margaux, Bordeaux, France",
    "producer": "Ch\u00e2teau Margaux",
    "vintage": 2015.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 750,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Violet, plum, silky tannins.",
    "image": NaN,
    "slug": "ch-teau-margaux-2015"
  },
  {
    "id": "ad9195b4-a847-4fde-9973-4ed28a907485",
    "name": "Ch\u00e2teau Latour 2009",
    "category": "wine",
    "subCategory": "Bordeaux First Growth",
    "region": "Pauillac, Bordeaux, France",
    "producer": "Ch\u00e2teau Latour",
    "vintage": 2009.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 980,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Dense blackberry, licorice, powerful structure.",
    "image": NaN,
    "slug": "ch-teau-latour-2009"
  },
  {
    "id": "2c5c9b1d-5ea2-422b-af61-e5feaab6e8ec",
    "name": "Ch\u00e2teau Haut-Brion 2010",
    "category": "wine",
    "subCategory": "Bordeaux First Growth",
    "region": "Pessac-L\u00e9ognan, Bordeaux, France",
    "producer": "Ch\u00e2teau Haut-Brion",
    "vintage": 2010.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 720,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Smoked earth, red currant, refined finish.",
    "image": NaN,
    "slug": "ch-teau-haut-brion-2010"
  },
  {
    "id": "a23a9950-5567-49a1-8dc9-3d1efa900886",
    "name": "Ch\u00e2teau Cheval Blanc 2015",
    "category": "wine",
    "subCategory": "Right Bank Premier Grand Cru A",
    "region": "Saint\u2011\u00c9milion, Bordeaux, France",
    "producer": "Ch\u00e2teau Cheval Blanc",
    "vintage": 2015.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 950,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Rose petal, cherry, velvet mouthfeel.",
    "image": NaN,
    "slug": "ch-teau-cheval-blanc-2015"
  },
  {
    "id": "8d858fee-ae94-4cce-b5a7-1e628c4bcb6f",
    "name": "Ch\u00e2teau Ausone 2010",
    "category": "wine",
    "subCategory": "Right Bank Premier Grand Cru A",
    "region": "Saint\u2011\u00c9milion, Bordeaux, France",
    "producer": "Ch\u00e2teau Ausone",
    "vintage": 2010.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 1400,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Mineral, dark fruit, elegant tannins.",
    "image": NaN,
    "slug": "ch-teau-ausone-2010"
  },
  {
    "id": "55138233-ec58-4cb1-b981-e0f9ea83ff63",
    "name": "Ch\u00e2teau P\u00e9trus 2015",
    "category": "wine",
    "subCategory": "Pomerol",
    "region": "Pomerol, Bordeaux, France",
    "producer": "Ch\u00e2teau P\u00e9trus",
    "vintage": 2015.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 3800,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Plum, truffle, plush texture.",
    "image": NaN,
    "slug": "ch-teau-p-trus-2015"
  },
  {
    "id": "258361bc-12d4-4b3d-9110-539f14cf8adf",
    "name": "Domaine de la Roman\u00e9e\u2011Conti Roman\u00e9e\u2011Conti 2016",
    "category": "wine",
    "subCategory": "Burgundy Grand Cru",
    "region": "Vosne\u2011Roman\u00e9e, C\u00f4te de Nuits, France",
    "producer": "DRC",
    "vintage": 2016.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 25000,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Exotic spice, rose, ethereal length.",
    "image": NaN,
    "slug": "domaine-de-la-roman-e-conti-roman-e-conti-2016"
  },
  {
    "id": "8403f15e-d78c-478e-a6a5-49a9f191c1e8",
    "name": "Domaine de la Roman\u00e9e\u2011Conti La T\u00e2che 2017",
    "category": "wine",
    "subCategory": "Burgundy Grand Cru",
    "region": "Vosne\u2011Roman\u00e9e, C\u00f4te de Nuits, France",
    "producer": "DRC",
    "vintage": 2017.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 6500,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Incense, wild strawberry, endless finish.",
    "image": NaN,
    "slug": "domaine-de-la-roman-e-conti-la-t-che-2017"
  },
  {
    "id": "a3f030ef-8de7-4de3-baba-d4b35d1b1c1c",
    "name": "Domaine de la Roman\u00e9e\u2011Conti Richebourg 2015",
    "category": "wine",
    "subCategory": "Burgundy Grand Cru",
    "region": "Vosne\u2011Roman\u00e9e, C\u00f4te de Nuits, France",
    "producer": "DRC",
    "vintage": 2015.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 6000,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Dark cherry, sandalwood, deep palate.",
    "image": NaN,
    "slug": "domaine-de-la-roman-e-conti-richebourg-2015"
  },
  {
    "id": "af9e1bd9-79f8-4c07-87e1-2dd0e06ff69e",
    "name": "Domaine Leroy Musigny 2019",
    "category": "wine",
    "subCategory": "Burgundy Grand Cru",
    "region": "Musigny, C\u00f4te de Nuits, France",
    "producer": "Domaine Leroy",
    "vintage": 2019.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 18000,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Crushed rose, red fruit purity.",
    "image": NaN,
    "slug": "domaine-leroy-musigny-2019"
  },
  {
    "id": "c3065c6d-38e4-4e6d-85ed-cd104fe98d40",
    "name": "Domaine Armand Rousseau Chambertin 2014",
    "category": "wine",
    "subCategory": "Burgundy Grand Cru",
    "region": "Gevrey\u2011Chambertin, C\u00f4te de Nuits, France",
    "producer": "Armand Rousseau",
    "vintage": 2014.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 3000,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Forest floor, blackberry, silky.",
    "image": NaN,
    "slug": "domaine-armand-rousseau-chambertin-2014"
  },
  {
    "id": "3b480fce-c195-4fd7-8a66-90499691fe3c",
    "name": "Domaine Leflaive Chevalier\u2011Montrachet 2018",
    "category": "wine",
    "subCategory": "Burgundy Grand Cru (White)",
    "region": "Puligny\u2011Montrachet, C\u00f4te de Beaune, France",
    "producer": "Domaine Leflaive",
    "vintage": 2018.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 1600,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Citrus, hazelnut, electric minerality.",
    "image": NaN,
    "slug": "domaine-leflaive-chevalier-montrachet-2018"
  },
  {
    "id": "95b3ef7a-5e63-4f80-b929-fc6d9acd6e2d",
    "name": "Domaine Coche\u2011Dury Corton\u2011Charlemagne 2020",
    "category": "wine",
    "subCategory": "Burgundy Grand Cru (White)",
    "region": "Aloxe\u2011Corton, C\u00f4te de Beaune, France",
    "producer": "Coche\u2011Dury",
    "vintage": 2020.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 4500,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Toasted almond, flint, laser focus.",
    "image": NaN,
    "slug": "domaine-coche-dury-corton-charlemagne-2020"
  },
  {
    "id": "70531853-3581-4170-a6b1-61a7bff69d85",
    "name": "Domaine Comte Liger\u2011Belair La Roman\u00e9e 2018",
    "category": "wine",
    "subCategory": "Burgundy Grand Cru",
    "region": "Vosne\u2011Roman\u00e9e, C\u00f4te de Nuits, France",
    "producer": "Comte Liger\u2011Belair",
    "vintage": 2018.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 9500,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Rose, spice, velvet texture.",
    "image": NaN,
    "slug": "domaine-comte-liger-belair-la-roman-e-2018"
  },
  {
    "id": "0bee458c-9cb7-47ea-a5f8-ebd9aeff3dcc",
    "name": "Henri Jayer Cros Parantoux 1999",
    "category": "spirit",
    "subCategory": "Burgundy Premier Cru",
    "region": "Vosne\u2011Roman\u00e9e, C\u00f4te de Nuits, France",
    "producer": "Henri Jayer",
    "vintage": 1999.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 28000,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Truffle, raspberry, profound depth.",
    "image": NaN,
    "slug": "henri-jayer-cros-parantoux-1999"
  },
  {
    "id": "a3f7b07a-a4c4-44fd-881f-de713834399d",
    "name": "Domaine Georges Roumier Musigny 2015",
    "category": "wine",
    "subCategory": "Burgundy Grand Cru",
    "region": "Musigny, C\u00f4te de Nuits, France",
    "producer": "Georges Roumier",
    "vintage": 2015.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 12000,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Tea leaf, cherry, silky power.",
    "image": NaN,
    "slug": "domaine-georges-roumier-musigny-2015"
  },
  {
    "id": "7beac7a1-f66c-438d-aa0c-3d310d28051b",
    "name": "Domaine M\u00e9o\u2011Camuzet Richebourg 2013",
    "category": "wine",
    "subCategory": "Burgundy Grand Cru",
    "region": "Vosne\u2011Roman\u00e9e, C\u00f4te de Nuits, France",
    "producer": "M\u00e9o\u2011Camuzet",
    "vintage": 2013.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 4200,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Spice box, dark berry, polished.",
    "image": NaN,
    "slug": "domaine-m-o-camuzet-richebourg-2013"
  },
  {
    "id": "2632169f-d879-4be3-8100-2be94d9e3361",
    "name": "Screaming Eagle Cabernet Sauvignon 2019",
    "category": "wine",
    "subCategory": "Napa Cult Wine",
    "region": "Oakville, Napa Valley, USA",
    "producer": "Screaming Eagle",
    "vintage": 2019.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 3800,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Blackberry, creme de cassis, plush tannins.",
    "image": NaN,
    "slug": "screaming-eagle-cabernet-sauvignon-2019"
  },
  {
    "id": "4687c14e-a29a-46dc-b7cd-6778be6faa1a",
    "name": "Harlan Estate 2018",
    "category": "wine",
    "subCategory": "Napa Cult Wine",
    "region": "Oakville, Napa Valley, USA",
    "producer": "Harlan Estate",
    "vintage": 2018.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 1600,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Chocolate, violet, opulent.",
    "image": NaN,
    "slug": "harlan-estate-2018"
  },
  {
    "id": "6c9e1d4f-5423-4bc4-86f5-cf9b1faaee93",
    "name": "Scarecrow Cabernet Sauvignon 2018",
    "category": "spirit",
    "subCategory": "Napa Cult Wine",
    "region": "Rutherford, Napa Valley, USA",
    "producer": "Scarecrow",
    "vintage": 2018.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 1200,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Blueberry, sage, fine tannins.",
    "image": NaN,
    "slug": "scarecrow-cabernet-sauvignon-2018"
  },
  {
    "id": "8970c57f-5269-4464-9f8d-69014ca6b525",
    "name": "Colgin IX Estate 2018",
    "category": "wine",
    "subCategory": "Napa Cult Wine",
    "region": "Pritchard Hill, Napa Valley, USA",
    "producer": "Colgin",
    "vintage": 2018.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 750,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Lavender, graphite, seamless.",
    "image": NaN,
    "slug": "colgin-ix-estate-2018"
  },
  {
    "id": "66b14fc9-4fa1-44fe-8514-4e836f82f509",
    "name": "Opus One 2019",
    "category": "spirit",
    "subCategory": "Napa Blend Icon",
    "region": "Oakville, Napa Valley, USA",
    "producer": "Opus One",
    "vintage": 2019.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 425,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Black cherry, mocha, balanced.",
    "image": NaN,
    "slug": "opus-one-2019"
  },
  {
    "id": "e10eb835-90e9-4383-acda-5c26d0ff9d26",
    "name": "Dominus Estate 2018",
    "category": "wine",
    "subCategory": "Napa Blend Icon",
    "region": "Yountville, Napa Valley, USA",
    "producer": "Dominus Estate",
    "vintage": 2018.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 360,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Plum, tobacco, savory finish.",
    "image": NaN,
    "slug": "dominus-estate-2018"
  },
  {
    "id": "97df8071-9886-440a-971c-9a0d302660d1",
    "name": "Bryant Family Cabernet 2016",
    "category": "spirit",
    "subCategory": "Napa Cult Wine",
    "region": "Pritchard Hill, Napa Valley, USA",
    "producer": "Bryant Family",
    "vintage": 2016.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 650,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Black fruit, violets, layered.",
    "image": NaN,
    "slug": "bryant-family-cabernet-2016"
  },
  {
    "id": "f4733775-17dc-4f76-afae-be956f4358fe",
    "name": "Sloan Estate 2018",
    "category": "wine",
    "subCategory": "Napa Cult Wine",
    "region": "Rutherford, Napa Valley, USA",
    "producer": "Sloan Estate",
    "vintage": 2018.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 500,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Cassis, spice, muscular frame.",
    "image": NaN,
    "slug": "sloan-estate-2018"
  },
  {
    "id": "be848c3e-9fd2-48c0-b388-df7bc3ef3199",
    "name": "Hundred Acre Kayli Morgan 2015",
    "category": "spirit",
    "subCategory": "Napa Cult Wine",
    "region": "Saint Helena, Napa Valley, USA",
    "producer": "Hundred Acre",
    "vintage": 2015.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 725,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Sweet berry, licorice, plush.",
    "image": NaN,
    "slug": "hundred-acre-kayli-morgan-2015"
  },
  {
    "id": "98d264fe-ed32-4f20-8475-23c3c9637441",
    "name": "Bond St. Eden 2017",
    "category": "spirit",
    "subCategory": "Napa Cult Wine",
    "region": "Oakville, Napa Valley, USA",
    "producer": "Bond",
    "vintage": 2017.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 675,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Blackberry, crushed rock, tension.",
    "image": NaN,
    "slug": "bond-st-eden-2017"
  },
  {
    "id": "4145bd3c-8716-4ab0-958b-3d611ab2c37f",
    "name": "V\u00e9rit\u00e9 La Muse 2018",
    "category": "spirit",
    "subCategory": "Sonoma Icon",
    "region": "Sonoma County, USA",
    "producer": "V\u00e9rit\u00e9",
    "vintage": 2018.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 400,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Black plum, herbs, polished tannins.",
    "image": NaN,
    "slug": "v-rit-la-muse-2018"
  },
  {
    "id": "a8a6dd98-57d2-47d7-b380-686f3d5614ed",
    "name": "Penfolds Grange 2018",
    "category": "wine",
    "subCategory": "Australian Icon",
    "region": "South Australia",
    "producer": "Penfolds",
    "vintage": 2018.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 800,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Dark chocolate, blackberry, spice.",
    "image": NaN,
    "slug": "penfolds-grange-2018"
  },
  {
    "id": "c6fa1ba5-092e-4a8f-863a-2a6a33940a6e",
    "name": "Ch\u00e2teau d'Yquem 2009",
    "category": "wine",
    "subCategory": "Sauternes 1er Cru Sup\u00e9rieur",
    "region": "Sauternes, Bordeaux, France",
    "producer": "Ch\u00e2teau d'Yquem",
    "vintage": 2009.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 450,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Apricot, honey, vibrant acidity.",
    "image": NaN,
    "slug": "ch-teau-d-yquem-2009"
  },
  {
    "id": "e10e6aa9-abf5-4fca-b1c8-d043c6c7a872",
    "name": "Sine Qua Non 'Piranha' Syrah 2016",
    "category": "spirit",
    "subCategory": "California Cult Rh\u00f4ne",
    "region": "Central Coast, California, USA",
    "producer": "Sine Qua Non",
    "vintage": 2016.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 450,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Black olive, smoke, viscous.",
    "image": NaN,
    "slug": "sine-qua-non-piranha-syrah-2016"
  },
  {
    "id": "a1ebb517-eb44-40e2-911a-ab40ae045c7e",
    "name": "Masseto 2018",
    "category": "wine",
    "subCategory": "Tuscan Merlot",
    "region": "Tuscany, Italy",
    "producer": "Masseto",
    "vintage": 2018.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 850,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Chocolate, plum, saline finish.",
    "image": NaN,
    "slug": "masseto-2018"
  },
  {
    "id": "4752c9fe-b894-44ea-9e70-8678ae26fc04",
    "name": "Sassicaia 2016",
    "category": "spirit",
    "subCategory": "Super Tuscan",
    "region": "Tuscany, Italy",
    "producer": "Tenuta San Guido",
    "vintage": 2016.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 450,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Currant, cedar, elegant.",
    "image": NaN,
    "slug": "sassicaia-2016"
  },
  {
    "id": "54d4c0f4-40f6-4dd9-87e3-14670ff42bf5",
    "name": "Ornellaia 2018",
    "category": "spirit",
    "subCategory": "Super Tuscan",
    "region": "Tuscany, Italy",
    "producer": "Ornellaia",
    "vintage": 2018.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 250,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Red berry, tobacco, polished.",
    "image": NaN,
    "slug": "ornellaia-2018"
  },
  {
    "id": "ad6c1d02-ab08-4591-96ad-0f54724587bd",
    "name": "Vega Sicilia \u00danico 2012",
    "category": "spirit",
    "subCategory": "Spanish Icon",
    "region": "Ribera del Duero, Spain",
    "producer": "Vega Sicilia",
    "vintage": 2012.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 425,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Black fruit, graphite, long.",
    "image": NaN,
    "slug": "vega-sicilia-nico-2012"
  },
  {
    "id": "f7ed0375-04cf-451d-bd0e-232e5799c74f",
    "name": "Ch\u00e2teau Palmer 2018",
    "category": "wine",
    "subCategory": "Bordeaux Super Second",
    "region": "Margaux, Bordeaux, France",
    "producer": "Ch\u00e2teau Palmer",
    "vintage": 2018.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 350,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Floral, blueberry, silky.",
    "image": NaN,
    "slug": "ch-teau-palmer-2018"
  },
  {
    "id": "9f9047f1-7839-44fd-8372-f83ae94df25f",
    "name": "Ch\u00e2teau Ducru\u2011Beaucaillou 2018",
    "category": "wine",
    "subCategory": "Bordeaux Super Second",
    "region": "Saint\u2011Julien, Bordeaux, France",
    "producer": "Ch\u00e2teau Ducru\u2011Beaucaillou",
    "vintage": 2018.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 250,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Mineral, cassis, refined.",
    "image": NaN,
    "slug": "ch-teau-ducru-beaucaillou-2018"
  },
  {
    "id": "266b6433-2f5d-48c4-b09e-ebd9917640fd",
    "name": "Ch\u00e2teau L\u00e9oville Las Cases 2018",
    "category": "wine",
    "subCategory": "Bordeaux Super Second",
    "region": "Saint\u2011Julien, Bordeaux, France",
    "producer": "Ch\u00e2teau L\u00e9oville Las Cases",
    "vintage": 2018.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 275,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Graphite, blackberry, profound.",
    "image": NaN,
    "slug": "ch-teau-l-oville-las-cases-2018"
  },
  {
    "id": "1a9ef7d2-0d9d-4458-acf1-14738690fd80",
    "name": "Ch\u00e2teau Montrose 2016",
    "category": "wine",
    "subCategory": "Bordeaux Super Second",
    "region": "Saint\u2011Est\u00e8phe, Bordeaux, France",
    "producer": "Ch\u00e2teau Montrose",
    "vintage": 2016.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 220,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Licorice, plum, firm structure.",
    "image": NaN,
    "slug": "ch-teau-montrose-2016"
  },
  {
    "id": "a4e60c4f-6e7f-41cd-87d1-f8056049451d",
    "name": "Ch\u00e2teau Pichon Comtesse 2018",
    "category": "wine",
    "subCategory": "Bordeaux Super Second",
    "region": "Pauillac, Bordeaux, France",
    "producer": "Ch\u00e2teau Pichon Comtesse de Lalande",
    "vintage": 2018.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 210,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Blackcurrant, floral, elegance.",
    "image": NaN,
    "slug": "ch-teau-pichon-comtesse-2018"
  },
  {
    "id": "085f89cd-2694-4290-b7ee-93bfcf5cc0da",
    "name": "Ch\u00e2teau Canon 2016",
    "category": "wine",
    "subCategory": "Saint\u2011\u00c9milion Premier Grand Cru B",
    "region": "Saint\u2011\u00c9milion, Bordeaux, France",
    "producer": "Ch\u00e2teau Canon",
    "vintage": 2016.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 180,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Red cherry, spice, finesse.",
    "image": NaN,
    "slug": "ch-teau-canon-2016"
  },
  {
    "id": "4e93dd50-689b-4de1-9c60-323f7a9a78b2",
    "name": "Ch\u00e2teau Figeac 2018",
    "category": "wine",
    "subCategory": "Saint\u2011\u00c9milion Premier Grand Cru A",
    "region": "Saint\u2011\u00c9milion, Bordeaux, France",
    "producer": "Ch\u00e2teau Figeac",
    "vintage": 2018.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 230,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Blackberry, mint, silky.",
    "image": NaN,
    "slug": "ch-teau-figeac-2018"
  },
  {
    "id": "35dcc678-602d-4416-8632-47bebbeee788",
    "name": "Ch\u00e2teau Pavie 2016",
    "category": "wine",
    "subCategory": "Saint\u2011\u00c9milion Premier Grand Cru A",
    "region": "Saint\u2011\u00c9milion, Bordeaux, France",
    "producer": "Ch\u00e2teau Pavie",
    "vintage": 2016.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 240,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Plum, mocha, powerful.",
    "image": NaN,
    "slug": "ch-teau-pavie-2016"
  },
  {
    "id": "972f4057-10aa-469e-b21b-6229b2726c0e",
    "name": "Clos Rougeard Le Bourg 2015",
    "category": "spirit",
    "subCategory": "Loire Valley Cult",
    "region": "Saumur\u2011Champigny, Loire, France",
    "producer": "Clos Rougeard",
    "vintage": 2015.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 650,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Red fruit, earth, purity.",
    "image": NaN,
    "slug": "clos-rougeard-le-bourg-2015"
  },
  {
    "id": "36440a49-1859-4adc-aa99-ee273f5e9ace",
    "name": "Domaine Huet Clos du Bourg Moelleux 2015",
    "category": "wine",
    "subCategory": "Loire Chenin (Sweet)",
    "region": "Vouvray, Loire, France",
    "producer": "Domaine Huet",
    "vintage": 2015.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 90,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Honey, peach, vibrant acidity.",
    "image": NaN,
    "slug": "domaine-huet-clos-du-bourg-moelleux-2015"
  },
  {
    "id": "6c188628-7061-4d9e-90d1-1310bd337c76",
    "name": "Ch\u00e2teau Rayas Ch\u00e2teauneuf\u2011du\u2011Pape 2010",
    "category": "wine",
    "subCategory": "Rhone Icon",
    "region": "Ch\u00e2teauneuf\u2011du\u2011Pape, Rh\u00f4ne, France",
    "producer": "Ch\u00e2teau Rayas",
    "vintage": 2010.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 1100,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Strawberry, garrigue, elegance.",
    "image": NaN,
    "slug": "ch-teau-rayas-ch-teauneuf-du-pape-2010"
  },
  {
    "id": "bac62678-bd90-4f11-9f27-e1e77a8026b0",
    "name": "Ridge Monte Bello 2018",
    "category": "spirit",
    "subCategory": "California Icon",
    "region": "Santa Cruz Mountains, California, USA",
    "producer": "Ridge Vineyards",
    "vintage": 2018.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 225,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Blackberry, cedar, cool-climate structure.",
    "image": NaN,
    "slug": "ridge-monte-bello-2018"
  },
  {
    "id": "df3a320b-8dd2-42ae-befb-0f143da5190f",
    "name": "Gaja Barbaresco 2016",
    "category": "spirit",
    "subCategory": "Italian Icon",
    "region": "Barbaresco, Piedmont, Italy",
    "producer": "Gaja",
    "vintage": 2016.0,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 300,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Cherry, tar, rose petals.",
    "image": NaN,
    "slug": "gaja-barbaresco-2016"
  },
  {
    "id": "5df35afa-34e3-40c7-aee1-2bb0317a28f2",
    "name": "Macallan 1926 Fine & Rare",
    "category": "spirit",
    "subCategory": "Rare Scotch",
    "region": "Speyside, Scotland",
    "producer": "The Macallan",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 2700000,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Dried fruit, resin, antique oak.",
    "image": NaN,
    "slug": "macallan-1926-fine-rare"
  },
  {
    "id": "df966ce0-8fec-4de7-8fcb-299fa8e78b72",
    "name": "Macallan Lalique 72 Year Old Genesis",
    "category": "spirit",
    "subCategory": "Rare Scotch",
    "region": "Speyside, Scotland",
    "producer": "The Macallan",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 82000,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Rich raisin, chocolate, long.",
    "image": NaN,
    "slug": "macallan-lalique-72-year-old-genesis"
  },
  {
    "id": "1fee91d0-04c8-4aa2-8015-6614f5e88a4e",
    "name": "Macallan M Black",
    "category": "spirit",
    "subCategory": "Collectible Scotch",
    "region": "Speyside, Scotland",
    "producer": "The Macallan",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 6800,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Sherry, fig, spice.",
    "image": NaN,
    "slug": "macallan-m-black"
  },
  {
    "id": "35670ca7-bc3f-433c-81d4-50058157f363",
    "name": "Yamazaki 55 Year Old",
    "category": "spirit",
    "subCategory": "Japanese Single Malt",
    "region": "Osaka, Japan",
    "producer": "Suntory",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 600000,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Layered sandalwood, tropical fruit.",
    "image": NaN,
    "slug": "yamazaki-55-year-old"
  },
  {
    "id": "cdc23dc9-4db4-4476-abad-65a433027c12",
    "name": "Yamazaki 25 Year Old",
    "category": "spirit",
    "subCategory": "Japanese Single Malt",
    "region": "Osaka, Japan",
    "producer": "Suntory",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 5100,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Dark chocolate, coffee, umami.",
    "image": NaN,
    "slug": "yamazaki-25-year-old"
  },
  {
    "id": "727126c6-39c3-4580-9b4a-0cce5e1a501b",
    "name": "Hibiki 21 Year Old",
    "category": "spirit",
    "subCategory": "Japanese Blended Whisky",
    "region": "Osaka, Japan",
    "producer": "Suntory",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 1400,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Plum, incense, harmony.",
    "image": NaN,
    "slug": "hibiki-21-year-old"
  },
  {
    "id": "25f3dc36-fd96-4c2e-8ade-f52e6b399f0c",
    "name": "Karuizawa 1960 'The Dragon'",
    "category": "spirit",
    "subCategory": "Japanese Single Malt",
    "region": "Nagano, Japan",
    "producer": "Karuizawa",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 320000,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Leather, dark fruit, intense.",
    "image": NaN,
    "slug": "karuizawa-1960-the-dragon"
  },
  {
    "id": "cd2c4ef7-84c8-4d41-a0db-11947b65cb5b",
    "name": "Hakushu 25 Year Old",
    "category": "spirit",
    "subCategory": "Japanese Single Malt",
    "region": "Yamanashi, Japan",
    "producer": "Suntory",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 7200,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Mint, smoke, citrus.",
    "image": NaN,
    "slug": "hakushu-25-year-old"
  },
  {
    "id": "cc4f7cf6-4bef-4f26-b576-9e493b8c5222",
    "name": "Pappy Van Winkle Family Reserve 23 Year",
    "category": "spirit",
    "subCategory": "Limited Bourbon",
    "region": "Kentucky, USA",
    "producer": "Old Rip Van Winkle Distillery",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 5200,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Vanilla, oak, caramel.",
    "image": NaN,
    "slug": "pappy-van-winkle-family-reserve-23-year"
  },
  {
    "id": "3c86c096-3331-46b3-a10e-89dd126a3746",
    "name": "Pappy Van Winkle Family Reserve 20 Year",
    "category": "spirit",
    "subCategory": "Limited Bourbon",
    "region": "Kentucky, USA",
    "producer": "Old Rip Van Winkle Distillery",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 3800,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Toffee, spice, smooth.",
    "image": NaN,
    "slug": "pappy-van-winkle-family-reserve-20-year"
  },
  {
    "id": "3a1d8f24-295d-4760-b4f3-a0556af148a2",
    "name": "George T. Stagg 2024 (BTAC)",
    "category": "spirit",
    "subCategory": "Limited Bourbon",
    "region": "Kentucky, USA",
    "producer": "Buffalo Trace",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 1200,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Dark cocoa, cherry, powerful.",
    "image": NaN,
    "slug": "george-t-stagg-2024-btac"
  },
  {
    "id": "b4340df1-ae63-4f6b-8b76-12f1d01b7627",
    "name": "William Larue Weller 2024 (BTAC)",
    "category": "spirit",
    "subCategory": "Limited Bourbon",
    "region": "Kentucky, USA",
    "producer": "Buffalo Trace",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 950,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Butterscotch, oak, rich.",
    "image": NaN,
    "slug": "william-larue-weller-2024-btac"
  },
  {
    "id": "90971046-b168-453e-b88b-927cfcc89038",
    "name": "E.H. Taylor Four Grain",
    "category": "spirit",
    "subCategory": "Limited Bourbon",
    "region": "Kentucky, USA",
    "producer": "Buffalo Trace",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 2500,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Honey, grain, baking spice.",
    "image": NaN,
    "slug": "e-h-taylor-four-grain"
  },
  {
    "id": "ca2cf153-b40a-4dbc-bb08-3cf4c882e963",
    "name": "Michter's Celebration Sour Mash 2023",
    "category": "spirit",
    "subCategory": "Limited Bourbon",
    "region": "Kentucky, USA",
    "producer": "Michter's",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 6000,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Citrus, vanilla, depth.",
    "image": NaN,
    "slug": "michter-s-celebration-sour-mash-2023"
  },
  {
    "id": "831db158-83ca-46e4-a282-2fed31133d4d",
    "name": "Willett Family Estate 17 Year",
    "category": "wine",
    "subCategory": "Limited Bourbon",
    "region": "Kentucky, USA",
    "producer": "Willett",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 1800,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Cherry, oak, sweet spice.",
    "image": NaN,
    "slug": "willett-family-estate-17-year"
  },
  {
    "id": "5199ae01-15f9-4421-b113-7463b41273cf",
    "name": "Old Rip Van Winkle 10 Year",
    "category": "spirit",
    "subCategory": "Limited Bourbon",
    "region": "Kentucky, USA",
    "producer": "Old Rip Van Winkle Distillery",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 1100,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Caramel, vanilla, oak.",
    "image": NaN,
    "slug": "old-rip-van-winkle-10-year"
  },
  {
    "id": "b02921e3-db00-4d5a-8ed6-b4b7df5a95e5",
    "name": "Blanton's Straight From The Barrel",
    "category": "spirit",
    "subCategory": "Single Barrel Bourbon",
    "region": "Kentucky, USA",
    "producer": "Buffalo Trace",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 300,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Brown sugar, spice, heat.",
    "image": NaN,
    "slug": "blanton-s-straight-from-the-barrel"
  },
  {
    "id": "a71fbdc3-a3ca-4682-8406-92f60d86b06b",
    "name": "Colonel E.H. Taylor Barrel Proof",
    "category": "spirit",
    "subCategory": "Limited Bourbon",
    "region": "Kentucky, USA",
    "producer": "Buffalo Trace",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 400,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Cinnamon, leather, robust.",
    "image": NaN,
    "slug": "colonel-e-h-taylor-barrel-proof"
  },
  {
    "id": "6f01bd72-d511-4b94-aaf5-973d3c65998b",
    "name": "Glenfiddich 50 Year Old",
    "category": "spirit",
    "subCategory": "Rare Scotch",
    "region": "Speyside, Scotland",
    "producer": "Glenfiddich",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 42000,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Orange peel, oak, elegance.",
    "image": NaN,
    "slug": "glenfiddich-50-year-old"
  },
  {
    "id": "2e12b9e3-3083-4c9a-9cb2-830e42e64dc9",
    "name": "GlenDronach 1972 Single Cask",
    "category": "spirit",
    "subCategory": "Rare Scotch",
    "region": "Highlands, Scotland",
    "producer": "GlenDronach",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 8800,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Treacle, fig, long finish.",
    "image": NaN,
    "slug": "glendronach-1972-single-cask"
  },
  {
    "id": "c5c683b3-13b3-4611-9a8f-34488861dd2a",
    "name": "Dalmore 62 Year Old",
    "category": "spirit",
    "subCategory": "Rare Scotch",
    "region": "Highlands, Scotland",
    "producer": "Dalmore",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 220000,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Coffee, marmalade, deep.",
    "image": NaN,
    "slug": "dalmore-62-year-old"
  },
  {
    "id": "9a516298-2dba-46dc-a9b5-9d8f5faae474",
    "name": "Highland Park 50 Year Old",
    "category": "spirit",
    "subCategory": "Rare Scotch",
    "region": "Orkney, Scotland",
    "producer": "Highland Park",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 16500,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Heather honey, smoke, balanced.",
    "image": NaN,
    "slug": "highland-park-50-year-old"
  },
  {
    "id": "0f2b2857-6538-4140-8f1e-e56001700ae2",
    "name": "Springbank 25 Year Old",
    "category": "spirit",
    "subCategory": "Rare Scotch",
    "region": "Campbeltown, Scotland",
    "producer": "Springbank",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 900,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Salted caramel, peat, complexity.",
    "image": NaN,
    "slug": "springbank-25-year-old"
  },
  {
    "id": "9ee281d7-0a43-49b3-a014-2ac42f256603",
    "name": "Port Ellen 39 Year Old 'Untold Stories'",
    "category": "spirit",
    "subCategory": "Rare Scotch",
    "region": "Islay, Scotland",
    "producer": "Port Ellen",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 10000,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Sea breeze, lemon, smoke.",
    "image": NaN,
    "slug": "port-ellen-39-year-old-untold-stories"
  },
  {
    "id": "5dbf4d27-ef69-4e8f-a315-79b5b166274b",
    "name": "Ardbeg 28 Year Old (1992)",
    "category": "spirit",
    "subCategory": "Rare Scotch",
    "region": "Islay, Scotland",
    "producer": "Ardbeg",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 8000,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Soot, tropical fruit, peat.",
    "image": NaN,
    "slug": "ardbeg-28-year-old-1992"
  },
  {
    "id": "f326a85c-8964-4513-86a2-3bb37872ed12",
    "name": "Laphroaig 30 Year Old",
    "category": "spirit",
    "subCategory": "Rare Scotch",
    "region": "Islay, Scotland",
    "producer": "Laphroaig",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 2500,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Medicinal, coconut, smoke.",
    "image": NaN,
    "slug": "laphroaig-30-year-old"
  },
  {
    "id": "d9f68092-97de-4667-a5d2-407790a3cb80",
    "name": "Talisker 41 Year Old",
    "category": "spirit",
    "subCategory": "Rare Scotch",
    "region": "Islands, Scotland",
    "producer": "Talisker",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 10500,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Brine, pepper, sweetness.",
    "image": NaN,
    "slug": "talisker-41-year-old"
  },
  {
    "id": "324b9408-2c98-466e-b05d-cde1e4831afa",
    "name": "Lagavulin 37 Year Old",
    "category": "spirit",
    "subCategory": "Rare Scotch",
    "region": "Islay, Scotland",
    "producer": "Lagavulin",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 8500,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Tea, iodine, dark chocolate.",
    "image": NaN,
    "slug": "lagavulin-37-year-old"
  },
  {
    "id": "64ba340f-af6c-4032-8ceb-97f2c0a46cd4",
    "name": "Bruichladdich Black Art 10",
    "category": "spirit",
    "subCategory": "Limited Scotch",
    "region": "Islay, Scotland",
    "producer": "Bruichladdich",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 550,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Fruit cake, smoke, chocolate.",
    "image": NaN,
    "slug": "bruichladdich-black-art-10"
  },
  {
    "id": "9621d043-12ff-4c2c-804e-a99b19efb865",
    "name": "Glenmorangie Pride 1974",
    "category": "spirit",
    "subCategory": "Rare Scotch",
    "region": "Highlands, Scotland",
    "producer": "Glenmorangie",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 17000,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Apricot, spice, silk.",
    "image": NaN,
    "slug": "glenmorangie-pride-1974"
  },
  {
    "id": "9d479a3c-90ca-48d0-9939-0d11f6c57d4f",
    "name": "Balvenie 1973 Rare Cask",
    "category": "spirit",
    "subCategory": "Rare Scotch",
    "region": "Speyside, Scotland",
    "producer": "Balvenie",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 9500,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Honey, oak, dried fruit.",
    "image": NaN,
    "slug": "balvenie-1973-rare-cask"
  },
  {
    "id": "91c956ac-016a-4bad-9f14-874c3523387b",
    "name": "Mortlach 1952 Gordon & MacPhail",
    "category": "spirit",
    "subCategory": "Rare Scotch",
    "region": "Speyside, Scotland",
    "producer": "Mortlach",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 24000,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Meatiness, clove, depth.",
    "image": NaN,
    "slug": "mortlach-1952-gordon-macphail"
  },
  {
    "id": "7055509b-af7b-4574-90ae-8d9618ebb2e2",
    "name": "Glen Grant 1953 Gordon & MacPhail",
    "category": "spirit",
    "subCategory": "Rare Scotch",
    "region": "Speyside, Scotland",
    "producer": "Glen Grant",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 18000,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Vanilla, almond, herbs.",
    "image": NaN,
    "slug": "glen-grant-1953-gordon-macphail"
  },
  {
    "id": "44742a39-c6d1-425b-821f-5b788297af36",
    "name": "Courvoisier L'Essence",
    "category": "spirit",
    "subCategory": "Vintage Cognac",
    "region": "Jarnac, France",
    "producer": "Courvoisier",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 3500,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Cocoa, leather, floral.",
    "image": NaN,
    "slug": "courvoisier-l-essence"
  },
  {
    "id": "4e36fb88-e7d8-487f-898b-84d52be03bd7",
    "name": "Hennessy Paradis Imperial",
    "category": "spirit",
    "subCategory": "Vintage Cognac",
    "region": "Cognac, France",
    "producer": "Hennessy",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 3800,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Jasmine, spice, elegance.",
    "image": NaN,
    "slug": "hennessy-paradis-imperial"
  },
  {
    "id": "63d86090-6b59-459f-b53f-0ad4937f1aed",
    "name": "Remy Martin Louis XIII Rare Cask 42.1",
    "category": "spirit",
    "subCategory": "Vintage Cognac",
    "region": "Cognac, France",
    "producer": "R\u00e9my Martin",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 43000,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Plum, sandalwood, depth.",
    "image": NaN,
    "slug": "remy-martin-louis-xiii-rare-cask-42-1"
  },
  {
    "id": "a4370386-478d-4037-b8e1-d38e366e79fb",
    "name": "Delamain Le Voyage",
    "category": "spirit",
    "subCategory": "Vintage Cognac",
    "region": "Cognac, France",
    "producer": "Delamain",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 9000,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Vanilla bean, walnut, length.",
    "image": NaN,
    "slug": "delamain-le-voyage"
  },
  {
    "id": "4d978a3e-f7c2-4bd2-a252-512ed0892512",
    "name": "Camus Extra Dark & Intense",
    "category": "spirit",
    "subCategory": "Vintage Cognac",
    "region": "Cognac, France",
    "producer": "Camus",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 750,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Dark fruit, espresso, oak.",
    "image": NaN,
    "slug": "camus-extra-dark-intense"
  },
  {
    "id": "7f0f5048-2084-4c2b-bc8d-964aa4b4d572",
    "name": "Martell L'Or de Jean Martell",
    "category": "spirit",
    "subCategory": "Vintage Cognac",
    "region": "Cognac, France",
    "producer": "Martell",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 3800,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Fig, cedar, richness.",
    "image": NaN,
    "slug": "martell-l-or-de-jean-martell"
  },
  {
    "id": "8725bced-c2d7-498e-8831-023091e4cc8b",
    "name": "Richard Hennessy",
    "category": "spirit",
    "subCategory": "Vintage Cognac",
    "region": "Cognac, France",
    "producer": "Hennessy",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 5000,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Hazelnut, spice, velvety.",
    "image": NaN,
    "slug": "richard-hennessy"
  },
  {
    "id": "31881f4a-9014-4cdb-9335-aaf5615b51ad",
    "name": "Armagnac Laubade 1942",
    "category": "spirit",
    "subCategory": "Vintage Armagnac",
    "region": "Gers, France",
    "producer": "Ch\u00e2teau de Laubade",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 4000,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Prune, coffee, rancio.",
    "image": NaN,
    "slug": "armagnac-laubade-1942"
  },
  {
    "id": "c9c3f684-c63f-4087-a09d-1063755de4eb",
    "name": "Caroni 1996 Rum",
    "category": "spirit",
    "subCategory": "Vintage Rum",
    "region": "Trinidad",
    "producer": "Caroni",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 1200,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Tar, pineapple, spice.",
    "image": NaN,
    "slug": "caroni-1996-rum"
  },
  {
    "id": "5f79363a-b230-4774-862d-99b29945f80e",
    "name": "Diplomatico Ambassador Selection Rum",
    "category": "spirit",
    "subCategory": "Limited Rum",
    "region": "Venezuela",
    "producer": "Diplomatico",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 250,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Molasses, tropical fruit, oak.",
    "image": NaN,
    "slug": "diplomatico-ambassador-selection-rum"
  },
  {
    "id": "f54216ca-9d6d-4031-8833-665221eeb476",
    "name": "Jefferson's Ocean Cask Strength",
    "category": "spirit",
    "subCategory": "Limited Bourbon",
    "region": "Kentucky, USA",
    "producer": "Jefferson's",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 150,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Sea salt, caramel, oak.",
    "image": NaN,
    "slug": "jefferson-s-ocean-cask-strength"
  },
  {
    "id": "9fa635b7-6da8-4c50-8881-a785648a328b",
    "name": "Kavalan Solist Vinho Barrique",
    "category": "spirit",
    "subCategory": "Single Cask Whisky",
    "region": "Taiwan",
    "producer": "Kavalan",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 350,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Mango, vanilla, toast.",
    "image": NaN,
    "slug": "kavalan-solist-vinho-barrique"
  },
  {
    "id": "37d8dfbe-6f44-4475-8617-0d51279bf4e6",
    "name": "Amrut Greedy Angels 12 Year",
    "category": "spirit",
    "subCategory": "Indian Single Malt",
    "region": "Bangalore, India",
    "producer": "Amrut",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 850,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Tropical, oak, spice.",
    "image": NaN,
    "slug": "amrut-greedy-angels-12-year"
  },
  {
    "id": "c85c8655-d682-445c-b01e-9deaa3167dd1",
    "name": "Midleton Very Rare Silent Distillery Chapter 3",
    "category": "spirit",
    "subCategory": "Irish Single Malt",
    "region": "Midleton, Ireland",
    "producer": "Midleton",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 49000,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Honeycomb, fruit, depth.",
    "image": NaN,
    "slug": "midleton-very-rare-silent-distillery-chapter-3"
  },
  {
    "id": "4855cd94-21c5-49e5-b2f3-1a4d4a853724",
    "name": "Brora 40 Year Old",
    "category": "spirit",
    "subCategory": "Rare Scotch",
    "region": "Highlands, Scotland",
    "producer": "Brora",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 11000,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Wax, peat, citrus.",
    "image": NaN,
    "slug": "brora-40-year-old"
  },
  {
    "id": "c1f0ec88-bd8c-49e0-891a-cbbd022544a0",
    "name": "Oban 32 Year Old",
    "category": "spirit",
    "subCategory": "Rare Scotch",
    "region": "Highlands, Scotland",
    "producer": "Oban",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 7800,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Sea salt, toffee, smoke.",
    "image": NaN,
    "slug": "oban-32-year-old"
  },
  {
    "id": "6a69ac4f-30c3-4aec-a7e5-2cf5da235e51",
    "name": "Booker's 30th Anniversary Bourbon",
    "category": "spirit",
    "subCategory": "Limited Bourbon",
    "region": "Kentucky, USA",
    "producer": "Booker's",
    "vintage": NaN,
    "bottleSize": "750 ml",
    "criticScore": NaN,
    "criticSource": NaN,
    "currentMarketPriceUSD": 600,
    "fiveYearPriceChangePct": NaN,
    "investmentPotential": "Blue\u2011chip collectible with strong demand and limited availability.",
    "marketTrend": "Secondary market prices trending upward over the past decade.",
    "provenance": "Sourced from reputable, temperature\u2011controlled storage.",
    "tastingNotes": "Peanut brittle, oak, power.",
    "image": NaN,
    "slug": "booker-s-30th-anniversary-bourbon"
  }
] as const;
